### ISSUE TITLE
[Noetic] Fields2Cover failing to build on all platforms

### ISSUE THREAD

**Issue by sloretz** [Fields2Cover/Fields2Cover#104]
* https://build.ros.org/view/Nbin_uF64/job/Nbin_uF64__fields2cover__ubuntu_focal_amd64__binary/47
* https://build.ros.org/view/Nbin_uF64/job/Nbin_uF64__fields2cover__ubuntu_focal_amd64__binary/46/
* https://build.ros.org/view/Nbin_ufv8_uFv8/job/Nbin_ufv8_uFv8__fields2cover__ubuntu_focal_arm64__binary/46/

```
23:16:00 CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
23:16:04   Could NOT find Python3 (missing: Python3_LIBRARIES Python3_INCLUDE_DIRS
23:16:04   Development) (found version "3.8.2")
23:16:04 Call Stack (most recent call first):
23:16:04   /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
23:16:04   /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
23:16:04   /usr/share/cmake-3.16/Modules/FindPython3.cmake:300 (include)
23:16:04   obj-aarch64-linux-gnu/_deps/matplotlib_cpp-src/CMakeLists.txt:31 (find_package)
```

It seems like the `package.xml` has the keys it needs for Python dependencies. Maybe it just needs a new release to fix?

https://github.com/Fields2Cover/Fields2Cover/blob/8bf28f7c5b6d8b8a2688aaa8fb1ac426e5c2d942/package.xml#L23-L24

**Comment by Gonzalo-Mier** [comment]
Hello @sloretz. Thank you for checking. We weren't sure what was happening. We are working on it now.

**Comment by Gonzalo-Mier** [comment]
Not working either. Same error

**Comment by Gonzalo-Mier** [comment]
Yes, it solved the issue. Thank you again @sloretz
