### ISSUE TITLE
a) how to launch the ros2 interface and b) how to import a field from a .shp format

### ISSUE THREAD

**Issue by helix22** [Fields2Cover/Fields2Cover#106]
Hello!! I will be as quick as possible and I will later on the delete the issue because I suspect I might be too noob.
a) I 've installed everything, but how do I launch the ros2 interface, as I see only a ROS 1 demo.
b) I cannot manage to get my field (in .shp via qgis) in a format readable by f2c (such as test1.xml). Any advice here? I tried many things among which saving the layer as gml, renaming it to .xml but still: Segmentation fault (core dumped).

Thanks A LOT for this awesome work.

**Comment by helix22** [comment]
Dear Gonzalo-Mier, thank you **very** much for this quick reply!!

Regarding the (1), okay good, I thought I was missing something, maybe I will try installing ROS1 to try it as well!
Regarding the (2), everything is clearer already, I just can't get to place my wkt data into the importFromWkt. Could you spend some more time in order to give me an example? i.e. if my field is this in WKT: "POLYGON ((571826.879847092 4454303.72791723,571995.622984484 4454429.58217387,572016.674058808 4454401.14195982,571852.381533276 4454277.61374514,571826.879847092 4454303.72791723))"

Thanks again!! :)

**Comment by Gonzalo-Mier** [comment]
Hi @helix22,

There is an example in [the tutorials](https://fields2cover.github.io/source/tutorials/basic_types.html#initialize-a-f2cpoint) on using importFromWkt for a point. Similarly, you can do the same with F2CCell. This is the code in python:

```
import fields2cover as f2c
c = f2c.Cell()
c.importFromWkt("POLYGON ((571826.879847092 4454303.72791723,571995.622984484 4454429.58217387,572016.674058808 4454401.14195982,571852.381533276 4454277.61374514,571826.879847092 4454303.72791723))")

f2c.Visualizer.figure()
f2c.Visualizer.plot(c)
f2c.Visualizer.show()
```
Hope this is useful!

**Comment by helix22** [comment]
Done! Great! Ok now I will try to import "c" in the complete flow as a field and transform it to UTM to work in meters.

So many thanks! :)

**Comment by Gonzalo-Mier** [comment]
The poligon you sent is already in UTM (and in meters). You dont have to
transform it.

**Comment by helix22** [comment]
Right! So the very last question of this thread would be.. Well obviously commenting out field = f2c.Parser... and the transform after, and even more obviously typing instead "field = c" (where c is my polygon that i imported from Wkt, for anyone checking please see above) does not work, so what am I missing for the n^th time? ('Cell' object has not attribute 'field'). A sincere apology for my lack of skills here.

**Comment by helix22** [comment]
Hello again! For the record and for anyone wondering in the future I sum up (please jump in where I am mistaken):

My query started since I could not transform the format of my field into the .xml format used in the tutorial 7_complete_flow. So, a field in a shp format, maybe from QGIS app (probably a number of files, 5 in my case: .cpg, .dbf, .shp, .prj, .shx) can be easily converted to WKT from here: https://mygeodata.cloud/converter/shp-to-wkt.

Then, you can create a Cell and import the polygon [as above](https://github.com/Fields2Cover/Fields2Cover/issues/106#issuecomment-1945849565).

Then you can use:

cells = f2c.Cells()
cells.addGeometry(c)

And if using the exact tutorial 7, you will have to switch the "field.field" in the no_hl = ... to "cells", and also in the plotting later, as you have not defined "field" anywhere. So, like this, you can import any field/polygon from wkt format and easily work on it.

Many thanks to  Gonzalo-Mier for the explanations.

**Comment by Rahul-Tom** [comment]
Hii there,
I am using Nav2 wrapper of F2C. I tried to create the GML file of my land using QGIS and I also got segmentation error when I use it. So how can I convert the land with existing rows into GML format that can be parsed with F2C?
