### ISSUE TITLE
ROS humble pkg not found with C++

### ISSUE THREAD

**Issue by JensOgorek** [Fields2Cover/Fields2Cover#107]
Hi,
I wanted to use the ROS2 version of Fields2Cover, but I can't get it to work.

For installation I used 
```sudo apt install ros-humble-fields2cover```
and ```find_package(Fields2Cover REQUIRED)``` in my CMakeList.txt

When trying to build the package I get 
```
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "FindFields2Cover.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Fields2Cover", but CMake did not find one.

  Could not find a package configuration file provided by "Fields2Cover" with
  any of the following names:

    Fields2CoverConfig.cmake
    fields2cover-config.cmake

  Add the installation prefix of "Fields2Cover" to CMAKE_PREFIX_PATH or set
  "Fields2Cover_DIR" to a directory containing one of the above files.  If
  "Fields2Cover" provides a separate development package or SDK, be sure it
  has been installed.

```
I used to build it myself and that worked. But using ros packages is more convenient. Any ideas that the problem might be?

**Comment by Gonzalo-Mier** [comment]
Hi @JensOgorek, welcome to the project.

That is an error that we plan to solve in the v2. The workaround for now is doing:
```
find_package(Fields2Cover REQUIRED HINTS "/opt/ros/humble/cmake")
```
