### ISSUE TITLE
Support more complicated shapes

### ISSUE THREAD

**Issue by jfulem** [Fields2Cover/Fields2Cover#11]
Please, @Gonzalo-Mier , do you think it would be possible to support more complicated shapes, such as:
![path-planning3](https://user-images.githubusercontent.com/14978902/184446166-fc360475-4db4-4103-b74f-5e9e853da66c.png)

where the path is located out of the field. I can work on this to fix it.
Thanks!

**Comment by Gonzalo-Mier** [comment]
I was planning to submit it in the next release (next year on may aprox). I cannot upload nothing earlier.  Feel free to work on this if you want. I would split it in:
- Going from end of swath A to start of swath B through the headlands (or any two points on the headlands)
- A decomposition algorithm, for example [Boustrophedon Cellular decomposition](https://link-springer-com.ezproxy.library.wur.nl/article/10.1023/A:1008958800904) 
- A route planner that finds the order to cover the decomposed cells.

Once you have the base class of any of those categories, submit a PR so we could discuss any change before start implementing it. Thank you for your time

**Comment by jfulem** [comment]
OK. I cannot access the article. I think we need that sooner than May 2023 so we will have to work on that. Than you.

**Comment by jfulem** [comment]
OK. I can take this one: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.69.2482&rep=rep1&type=pdf

**Comment by Gonzalo-Mier** [comment]
> OK. I cannot access the article. I think we need that sooner than May 2023 so we will have to work on that. Thank you.

Completely agree. It would be a great improvement.

**Comment by Gonzalo-Mier** [comment]
I'll close it as it has been without activity for 2 months now. We can open it later if needed

**Comment by vinnnyr** [comment]
hey @jfulem @Gonzalo-Mier , have either of you made headway on the cellular decomposition work / able to make it public?  This is also on my list of things to do, but I would love to know where you all stand. I also don't want to duplicate any work :)

**Comment by Gonzalo-Mier** [comment]
I was able to create the decomposition and improve the route planner, but not sure when I could release it. Next release I think will be around October - December, but not sure when.

What are you planning to do? And are you also planning to share it with the community? :)

**Comment by vinnnyr** [comment]
If I collaborate with someone here, then yes, the work will probably be shared as I would love to have it in the upstream. 
However, my goals are to handle this situation a bit sooner than October / December.  

Is there any way we can collaborate on the work you already have to expedite the release, or is it something out of your control? 

Even rough / alpha work that perhaps I (and others) can help test / bug hunt for would go a long way :) Otherwise we will have to duplicate some of this work with less of a chance it will end up in the upstream.

**Comment by Gonzalo-Mier** [comment]
Of course. I understand your concerns. Unfortunately, I'm not the one that decide when the next version is released, but I'll talk with them to see if we can do anything. 
I'll tell you something at the end of the next week :)

**Comment by Gonzalo-Mier** [comment]
Hi again @vinnnyr, 
Good news, they allow me to release the cellular decomposition methods (Trapezoidal and Boustrophedon decomposition) in its own branch. The cellular decomposition is a first step into solving the coverage path planning problem for non-convex field, but there are many things to do.

 If you want to continue from this point, feel free to propose new methods, a new interface for a new base class to, change whatever you need or discuss whatever you want. Of course would be nice to have you on board and collaborate together :)

**Comment by ingmeca2018** [comment]
Hi @vinnnyr @Gonzalo-Mier, any news about the work of the route planner that finds the order to cover the decomposed cells ?

**Comment by vinnnyr** [comment]
Sorry @ingmeca2018  I wish I had better news, but I have found still short on time. I will update here as I start looking into it.

**Comment by pvaiko** [comment]
I just bumped into this project. We have been generating paths for quite a while in a mod for the Farming Simulator game. We are currently refactoring the code as the quality if the old code is not the best.  The refactored code is in https://github.com/Courseplay/CourseGenerator if you want to take a look. 

We support complex polygons, islands in them and connect the blocks (or, as you call them cells) on the headland using a genetic algorithm to find the shortest path:
![image](https://github.com/Fields2Cover/Fields2Cover/assets/2379521/79bd6d9f-cc7d-4814-8f58-23382981b559)

**Comment by pvaiko** [comment]
As to the Lua support, I'm not a big fan of Lua, the only reason it is in Lua is that's what the game engine supports. I'd absolutely prefer some proper object oriented language, anything but Lua...

In any case, use the fields and whatever we you like from our repo. Let me know if you think I can help with anything.

**Comment by Gonzalo-Mier** [comment]
This issue should be solved on [v2 ](https://fields2cover.github.io/source/tutorials/route_planning.html#metaheuristics-for-route-planning)
