### ISSUE TITLE
ROS Compatibility - colcon build failed

### ISSUE THREAD

**Issue by dmjtian** [Fields2Cover/Fields2Cover#112]
Thanks for your project，I want to achieve your project and I clone the project to ubuntu 20.04 on VMware, but when I run:
`colcon build`

> It's tips:

> home/ymx/ljgh/build/fields2cover/_deps/tinyxml2-src/xmltest.cpp: In function ‘int main(int, const char**)’:
/home/ymx/ljgh/build/fields2cover/_deps/tinyxml2-src/xmltest.cpp:711:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  711 |     fgets( savedBuf, 256, saved );
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/ymx/ljgh/build/fields2cover/_deps/tinyxml2-src/xmltest.cpp:1195:9: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
 1195 |    fgets( buf, 1024, textfile );
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
Finished <<< fields2cover [4min 42s]
Starting >>> fields2cover_ros
stderr: fields2cover_ros                                    
/home/ymx/ljgh/src/fields2cover_ros/test/test_ros_conversor.cpp:49:25: error: expected constructor, destructor, or type conversion before ‘(’ token
   49 | INSTANTIATE_TEST_SUITE_P(
      |                         ^
/home/ymx/ljgh/src/fields2cover_ros/test/test_ros_conversor.cpp:53:57: error: expected unqualified-id before ‘,’ token
   53 |     std::tuple<float_t, float_t, float_t>{0.0, 0.0, 0.0},
      |                                                         ^
/home/ymx/ljgh/src/fields2cover_ros/test/test_ros_conversor.cpp:54:42: error: invalid declarator before ‘{’ token
   54 |     std::tuple<float_t, float_t, float_t>{1.2, 3.456, -7.9},
      |                                          ^
/home/ymx/ljgh/src/fields2cover_ros/test/test_ros_conversor.cpp:54:60: error: expected unqualified-id before ‘,’ token
   54 |     std::tuple<float_t, float_t, float_t>{1.2, 3.456, -7.9},
      |                                                            ^
/home/ymx/ljgh/src/fields2cover_ros/test/test_ros_conversor.cpp:55:42: error: invalid declarator before ‘{’ token
   55 |     std::tuple<float_t, float_t, float_t>{20001.2787878, -3.456, -0.0}
      |                                          ^
`

I try to change cmake version,but It's also doesn't work.

**Comment by Gonzalo-Mier** [comment]
We deprecated the ROS interface because [Nav2](https://github.com/open-navigation/opennav_coverage) offers better support.
