### ISSUE TITLE
Using enumerate on a Swaths object causes a segfault

### ISSUE THREAD

**Issue by kylona** [Fields2Cover/Fields2Cover#119]
We found a bug in Version 2. 

Trying to use enumerate on a Swaths object causes a segmentation fault. 

It appears that enumerate is going beyond the length of swaths.

Here is a minimal example (that runs nicely in `tests/python/types/Swaths_test.py`)

```
def test_fields2cover_swath_enumerate():
  n = 10;
  swaths = f2c.Swaths();
  for i in range(1, n + 1):
    swaths.emplace_back(f2c.LineString(f2c.VectorPoint(
            [f2c.Point(i, i), f2c.Point(i, i + 1)])), i);
  for idx, swath in enumerate(swaths):
    pass
  assert True
```

I suspect that this is not isolated to Swaths but this is where we found it first. 

Hoping to dig in and find the root cause soon but thought we would document it here first.

**Comment by ar0ser0** [comment]
Trying to get a better idea of the underlying issue. Why was this not an issue before v2. Were there changes made to `f2c::types::Swaths`? I don't see any changes in https://fields2cover.github.io/source/migration_to_v2.html

**Comment by Gonzalo-Mier** [comment]
It is fixed now. The swig interface had a bug that didn't check if the loop was getting out of the boundary. Feel free to reopen it if it happens again, and thank you for the issue!
