### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Klein237** [Fields2Cover/Fields2Cover#121]
In follow the instruction of this page https://fields2cover.github.io/source/installation.html .
On the compilation part, i have this error when i did the command `make ..` in the build directory 
Find here the output of the terminal 
`CMake Error at build/_deps/ortools-src/cmake/FindSCIP.cmake:67 (message):
  SCIP_ROOT: not found
Call Stack (most recent call first):
  build/_deps/ortools-src/cmake/deps.cmake:143 (find_package)
  build/_deps/ortools-src/CMakeLists.txt:424 (include)
`

**Comment by Gonzalo-Mier** [comment]
Hi @Klein237,

I don't have that much information to help you. Which is your system?

You can try to install [ortools](https://developers.google.com/optimization/install) from here

**Comment by Klein237** [comment]
i use Ubuntu 22.04

**Comment by Gonzalo-Mier** [comment]
Have you tried to install ortools as mentioned?

**Comment by Gonzalo-Mier** [comment]
I'll close it as there is no new interaction. Feel free to open it again if needed
