### ISSUE TITLE
Full path constrained within headland

### ISSUE THREAD

**Issue by Marnonel6** [Fields2Cover/Fields2Cover#122]
Hi,

Just a quick question. It seems like F2C does not constrain the turns to be within the headland? This is a safety concern as the headland usually is the 'safe' driving boundary/fence. See images below of the exact same path being generated for different headlands. Is this the intent?

![Screenshot from 2024-04-18 08-48-30](https://github.com/Fields2Cover/Fields2Cover/assets/60977336/44185ccc-d34d-4b40-a8e5-76e4ad1fe50f)

![Screenshot from 2024-04-18 08-51-41](https://github.com/Fields2Cover/Fields2Cover/assets/60977336/98824c56-27c4-4ddf-8b55-e00ac7f9be8f)

**Comment by Gonzalo-Mier** [comment]
Hi @Marnonel6, There is no way to constrain this in F2C yet. I also agree it is needed and it's a great addition, though I don't have time to implement those methods. If you need documentation, I can provide some :)

**Comment by Marnonel6** [comment]
Thank you for the information!
