### ISSUE TITLE
ROS buildfarm does not compile F2C properly

### ISSUE THREAD

**Issue by Gonzalo-Mier** [Fields2Cover/Fields2Cover#136]
Issue to discuss the progress about PR https://github.com/Fields2Cover/Fields2Cover/pull/133 and https://github.com/Fields2Cover/Fields2Cover/pull/134

**Comment by Gonzalo-Mier** [comment]
Error returned by: https://build.ros2.org/job/Rbin_uN64__fields2cover__ubuntu_noble_amd64__binary/68/consoleFull#console-section-16
```
08:29:21 CMake Error at CMakeLists.txt:129 (find_package):
08:29:21   Could not find a package configuration file provided by "ortools" with any
08:29:21   of the following names:
08:29:21 
08:29:21     ortoolsConfig.cmake
08:29:21     ortools-config.cmake
08:29:21 
08:29:21   Add the installation prefix of "ortools" to CMAKE_PREFIX_PATH or set
08:29:21   "ortools_DIR" to a directory containing one of the above files.  If
08:29:21   "ortools" provides a separate development package or SDK, be sure it has
08:29:21   been installed.
```

**Comment by aosmw** [comment]
The essence of the 1st build failure is replicated by the following script which effective comes from the  debhelper dh_auto_configure.
```
#!/bin/bash

mkdir -p build
cd build
DEB_PYTHON_INSTALL_LAYOUT=deb cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DBUILD_TESTING:BOOL=OFF -DCMAKE_INSTALL_PREFIX=/opt/ros/rolling -DCMAKE_PREFIX_PATH=/opt/ros/rolling -DBUILD_TESTING=OFF ..
```

The important setting being -DFETCHCONTENT_FULLY_DISCONNECTED=ON which fully disables the use of FetchContent during debian packaging.   The apparent reason why - https://salsa.debian.org/debian/debhelper/-/commit/5debbd6171dd2a091dde9ed499d8bb118ed2e1a8 
> cmake: set FETCHCONTENT_FULLY_DISCONNECTED to true
According to the documentation[1], FETCHCONTENT_FULLY_DISCONNECTED tells
the FetchContent module that no internet connection is available, and no
attempt at downloading dependencies at configure time is made, thus
speeding up builds.
> Debian package builds are already made offline, and I don't expect this
to create any issue for users; it is thus enabled regardless of the
dh-compat level.

which leads to 

https://cmake.org/cmake/help/latest/module/FetchContent.html#variable:FETCHCONTENT_FULLY_DISCONNECTED
which clarifies its intended use suggesting that this topic has been raised before.

> Note The FETCHCONTENT_FULLY_DISCONNECTED variable is not an appropriate way to prevent any network access on the first run in a build directory. Doing so can break projects, lead to misleading error messages, and hide subtle population failures. This variable is specifically intended to only be turned on after the first time CMake has been run. If you want to prevent network access even on the first run, use a [dependency provider](https://cmake.org/cmake/help/latest/command/cmake_language.html#dependency-providers) and populate the dependency from local content instead.



The ros2 helper ament_vendor() gets away with it because it uses cmake's ExternalProject which does not respect FETCHCONTENT_FULLY_DISCONNECTED=ON.  However ament_vendor does use `UPDATE_DISCONNECTED TRUE`.  `UPDATE_DISCONNECTED TRUE` skips the update step.  It does not prevent the initial download step.  
See https://github.com/ament/ament_cmake/blob/79cc237f8eb819edf4c1c624b56451e0a05a45f8/ament_cmake_vendor_package/cmake/ament_vendor.cmake#L290

And https://cmake.org/cmake/help/latest/module/ExternalProject.html#update-step-options

**Comment by aosmw** [comment]
rosbag2 mcap_vendor gets away with it by overriding the debian rules by appending 
`-DFETCHCONTENT_FULLY_DISCONNECTED=OFF`

See https://github.com/ros2-gbp/rosbag2-release/pull/10/files

**Comment by aosmw** [comment]
This is the file that I think needs to change and then the appropriate bloom commands run.
https://github.com/Fields2Cover/fields2cover-release/blob/debian/rolling/fields2cover/debian/rules.em

https://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty#Custom_Build_Commands

**Comment by aosmw** [comment]
Note tweak to debian build option to correct repository here https://github.com/ros2-gbp/fields2cover-release/commit/33742dfb56d0ac606037c74742356833568d093f

**Comment by Gonzalo-Mier** [comment]
Still not working. Now the main issue is "`/usr/bin/ld: _deps/ortools-src/lib/libortools.so.9.9.3963: error adding symbols: file in wrong format`" (https://build.ros2.org/job/Ibin_ujv8_uJv8__fields2cover__ubuntu_jammy_arm64__binary/85/consoleFull#console-section-16)

**Comment by aosmw** [comment]
> Still not working. Now the main issue is "`/usr/bin/ld: _deps/ortools-src/lib/libortools.so.9.9.3963: error adding symbols: file in wrong format`" (https://build.ros2.org/job/Ibin_ujv8_uJv8__fields2cover__ubuntu_jammy_arm64__binary/85/consoleFull#console-section-16)

This is because its an arm64 build variant.  The built release tarball being downloaded or ortools is for amd64.

**Comment by aosmw** [comment]
Here is an attempt at supporting a arm64 variant - https://github.com/Fields2Cover/Fields2Cover/pull/141

I don't have one so only the build farm will let me know it if works.

**Comment by aosmw** [comment]
https://build.ros2.org/job/Rbin_uJ64__fields2cover__ubuntu_jammy_amd64__binary/ is the build care about the most.  So YAY!

Rbin_uJ64 == Rolling Binary ubuntu jammy AMD64

**Comment by Gonzalo-Mier** [comment]
Unfortunately, for jammy the last version compiled was v1.2.1. For v2, check https://build.ros2.org/job/Rbin_uN64__fields2cover__ubuntu_noble_amd64__binary/

```
08:13:22 -- or-tools -- Downloading and installing from release tarball
08:13:22 CMake Error at CMakeLists.txt:129 (find_package):
08:13:22   Could not find a package configuration file provided by "ortools" with any
08:13:22   of the following names:
08:13:22 
08:13:22     ortoolsConfig.cmake
08:13:22     ortools-config.cmake
08:13:22 
08:13:22   Add the installation prefix of "ortools" to CMAKE_PREFIX_PATH or set
08:13:22   "ortools_DIR" to a directory containing one of the above files.  If
08:13:22   "ortools" provides a separate development package or SDK, be sure it has
08:13:22   been installed.
08:13:22 
08:13:22 
08:13:22 -- Configuring incomplete, errors occurred!
08:13:22 	cd .obj-x86_64-linux-gnu && tail -v -n \+0 CMakeCache.txt
08:13:22 dh_auto_configure: error: cd .obj-x86_64-linux-gnu && DEB_PYTHON_INSTALL_LAYOUT=deb cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DBUILD_TESTING:BOOL=OFF -DCMAKE_INSTALL_PREFIX=/opt/ros/rolling -DCMAKE_PREFIX_PATH=/opt/ros/rolling -DBUILD_TESTING=OFF .. returned exit code 1
08:13:22 make[1]: *** [debian/rules:36: override_dh_auto_configure] Error 2
```

I have seen that `DFETCHCONTENT_FULLY_DISCONNECTED=ON` on the error message above. `rules.em` was modified to disable it, tho

**Comment by aosmw** [comment]
> Unfortunately, for jammy the last version compiled was v1.2.1. For v2, check
Ah, spoke too soon.  Saw a green and mis-read the date.

I have never done a bloom release myself either.

I was hoping/guessing that a change to debian/rolling/fields2cover would be enough to cover all rolling branches.

... 

I see you just made some changes - https://github.com/ros2-gbp/fields2cover-release#fields2cover-rolling---200-12.  

Here's hoping.

**Comment by Gonzalo-Mier** [comment]
I've just released your PR to support arm. Lets see if that solves the problem. This is being harder than expected

**Comment by Gonzalo-Mier** [comment]
Awesome news!!!!! Green again for amd on everything, and for  arm only on rolling (due to being the only one released yesterday). I hope we can have everything green for amd and arm on the next release!!! Missing rhel6 tho, but maybe is being to ambitious.

https://build.ros2.org/job/Rbin_uN64__fields2cover__ubuntu_noble_amd64__binary/
https://build.ros2.org/job/Rbin_unv8_uNv8__fields2cover__ubuntu_noble_arm64__binary/
https://build.ros2.org/job/Jbin_uN64__fields2cover__ubuntu_noble_amd64__binary/
https://build.ros2.org/job/Ibin_uJ64__fields2cover__ubuntu_jammy_amd64__binary/
https://build.ros2.org/job/Hbin_uJ64__fields2cover__ubuntu_jammy_amd64__binary/

Thank you again @aosmw, I cannot stress you enough how good you are :clap:

**Comment by aosmw** [comment]
Great!!!

rhel6 is surely too old.  Got a link?

**Comment by Gonzalo-Mier** [comment]
https://build.ros2.org/job/Rbin_rhel_el964__fields2cover__rhel_9_x86_64__binary/186/consoleFull#console-section-14

**Comment by aosmw** [comment]
https://rhel.pkgs.org/9/epel-x86_64/geos-devel-3.10.1-1.el9.x86_64.rpm.html provides /usr/include/geos_c.h

**Comment by Gonzalo-Mier** [comment]
Thank you, I will try this

**Comment by Gonzalo-Mier** [comment]
As all the ROS versions are working now (except for rhel), I think we can safely close this issue. Thank you for your awesome work @aosmw!! I still can't believe it's working now
