### ISSUE TITLE
Packaging for distribution is needed, as the build subsequently fails because of the many unspecified dependencies

### ISSUE THREAD

**Issue by hsq125** [Fields2Cover/Fields2Cover#137]
cmake -DBUILD_PYTHON=ON ..;
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Could NOT find LAPACK (missing: LAPACK_LIBRARIES) 
    Reason given by package: LAPACK could not be found because dependency BLAS could not be found.

-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Could NOT find FFTW (missing: FFTW_INCLUDE_DIRS) 
Setting matplotplusplus compiler options
-- Using the multi-header code from /home/detailoc/dev/workspaces_no_backup/Fields2Cover/build/_deps/json-src/include/
-- Could NOT find Gnuplot (missing: GNUPLOT_EXECUTABLE) 
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GDAL: Found unsuitable version "GDAL_VERSION-NOTFOUND", but
  required is at least "3.0" (found GDAL_LIBRARY-NOTFOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindGDAL.cmake:185 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:112 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/detailoc/dev/workspaces_no_backup/Fields2Cover/build/CMakeFiles/CMakeOutput.log".
See also "/home/detailoc/dev/workspaces_no_backup/Fields2Cover/build/CMakeFiles/CMakeError.log".

This library is very difficult to install because of unspecified dependencies. I spent half a day to have it working on Ubuntu, without success :(

I think packages for the most important os/distributions are needed.

**Comment by hsq125** [comment]
As a workaround, I could have it working using the Dockerfile provided in the repo. 

build with 

`docker build  --tag f2c/f2c --file Dockerfile .`

run with 

`docker run -it f2c/f2c`

**Comment by Gonzalo-Mier** [comment]
As this issue didn't received any update, we'll close it. Feel free to open it again if needed.
