### ISSUE TITLE
Random class is based on rand_r(). Better if rand_r() is replaced by the <random> library

### ISSUE THREAD

**Issue by Gonzalo-Mier** [Fields2Cover/Fields2Cover#14]
This is a good issue to get used to the repository. `rand_r` is obsolete by POSIX.1-2008, which means in the future it may not work anymore. 

To solve this issue, the `f2c::Random` class (on files `include/fields2cover/utils/random.h` and `src/fields2cover/utils/random.cpp`) should be changed to use functions in the `<random>` lib instead of rand_r

**Comment by Gonzalo-Mier** [comment]
Cool video about this issue: https://www.youtube.com/watch?v=LDPMpc-ENqY

**Comment by mdabek** [comment]
You can assign this issue to me.
