### ISSUE TITLE
Planning of Loops F2c V2

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#150]
Hi!
I believe V2 sometimes now plans loops. I set up the V2 equivalent up of the minimal example shown here:
https://github.com/Fields2Cover/Fields2Cover/issues/75
```
import fields2cover as f2c

if __name__ == "__main__":
    # field
    rand = f2c.Random(42)
    field = rand.generateRandField(1e4, 5)
    cells = field.getField()
    # robot
    robot = f2c.Robot(2.0, 2.0)
    robot.setMinTurningRadius(1.0)
    # headlands
    const_hl = f2c.HG_Const_gen()
    no_hl = const_hl.generateHeadlands(cells, 3.0 * robot.getCovWidth())
    # swaths
    n_swath = f2c.OBJ_NSwath()
    bf_sw_gen = f2c.SG_BruteForce()
    swaths_bf_nswath = bf_sw_gen.generateBestSwaths(
        n_swath, robot.getCovWidth(), no_hl.getGeometry(0)
    )
    # swath ordering
    boustrophedon_sorter = f2c.RP_Boustrophedon()
    swaths = boustrophedon_sorter.genSortedSwaths(swaths_bf_nswath)
    # path
    path_planner = f2c.PP_PathPlanning()
    dubins_cc = f2c.PP_DubinsCurvesCC()
    path_dubins_cc = path_planner.planPath(robot, swaths, dubins_cc)
    # show
    f2c.Visualizer.figure()
    f2c.Visualizer.plot(path_dubins_cc)
    f2c.Visualizer.show()
```

![image](https://github.com/Fields2Cover/Fields2Cover/assets/22486686/4034a1a4-3b24-4633-af17-04b5be7c9bb2)

Did the fix applied in V1 get lost in the mix? I don't see any similar code to the loop detector
https://github.com/Fields2Cover/Fields2Cover/commit/68d5e79f2b88441201482f03d99d822f2351cfa4

Would you be opposed to a PR that adds that detector back in?

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr, PR merged.

**Comment by vinnnyr** [comment]
@Gonzalo-Mier  Can you explain how that heurisitc for removing loops works? 

Is there anything special about the contants used here?
```
    CC00_Dubins_State_Space ss(
        robot.getMaxCurv() / (1+0.05*n),
        robot.getMaxDiffCurv() / (1+0.2*n),
        discretization,
        true);
```
I am finding that I am still getting loops in certain situations, even with this patch merged in. I am having trouble tracking down if it's the heuristic, the max number of iterations, or the loop detection itself.

**Comment by Gonzalo-Mier** [comment]
We realized that making the maximum curvature and its diff smaller remove many of the loops. So basically if a loop is detected, we compute the same turn with smaller curv and diff curv. Constants are values that worked fine for our setting. Would be awesome to have a better solution than this

**Comment by vinnnyr** [comment]
@Gonzalo-Mier Maybe I am mistaken, but I actually think we want to make the max diff larger every iteration of this loop. 

Loops are caused by _overconstraining_ the problem, but making the max allowed curvature diff is adding more contraint. So I believe that we actually want 
```
   CC00_Dubins_State_Space ss(
        robot.getMaxCurv() / (1+0.05*n),
        robot.getMaxDiffCurv() * (1+0.2*n),
        discretization,
        true);
 ```

Maybe in your case, the reduction of max curvature overpowered the affect of changing the max diff so you haven't seen this issue yet.

Do you agree?

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr,
As mention in the PR, the max sharpness is a constrain because the sharpness should not be higher than that. In cases where sharpness is not a constrain, we could use Dubins instead assuming that max sharpness is infinite.

**Comment by vinnnyr** [comment]
Ok, good point.  I see what you are saying. For applications in which the sharpness bound needs to absolutely respected then yes my proposal would be a bad change.  I will think about this some more to see if there is something we can do to meet both use cases or figure out why I am seeing more loops than usual even with the original change merged in.

**Comment by Gonzalo-Mier** [comment]
Probably because the routes require middle points to travel through the headlands, which create those loops. I have tried to search a good solution but couldn't find one yet.

Do you think I need to revert the PR then?
