### ISSUE TITLE
Working with WGS84 

### ISSUE THREAD

**Issue by Marc-Morcos** [Fields2Cover/Fields2Cover#163]
While using open-navigation, I am having issues working with WGS84. Passing UTM:10N datum: WGS84 as the basis for a transform says that I am giving an invalid utm coordinate (My coordinates (x,y in wgs84) are -122.45457040980527, 38.1615260585674)

If I set frame to be `UTM:10N datum:WGS84` (Obtained by doing `"UTM:"+ str(math.floor((self.points[0][0] + 180) / 6) + 1) + ("N" if self.points[0][1] > 0 else "S") +" datum:WGS84"`)
I get
```
[interactive_waypoint_follower_fields-12] Navigating to with field of size: 5...
[component_container_isolated-11] [INFO] [1718921839.988349952] [bt_navigator]: Begin coverage navigating with outer field of size: 5!
[component_container_isolated-11] ERROR 1: PROJ: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone
[component_container_isolated-11] ERROR 1: PROJ: proj_create: unrecognized format / unknown name
```
If I set frame = `'EPSG:4326' `
I get 
```
enerating coverage path in EPSG:4326 frame for zone with 5 outer nodes and 0 inner polygons.
[component_container_isolated-11] [INFO] [1718922024.977691647] [controller_server]: Received a goal, begin computing control effort.
[component_container_isolated-11] [WARN] [1718922024.977737502] [controller_server]: No goal checker was specified in parameter 'current_goal_checker'. Server will use only plugin loaded general_goal_checker . This warning will appear once.
[component_container_isolated-11] [WARN] [1718922024.977746566] [controller_server]: No progress checker was specified in parameter 'current_progress_checker'. Server will use only plugin loaded progress_checker . This warning will appear once.
[component_container_isolated-11] [ERROR] [1718922025.038532812] [RPPPathHandler]: Exception in transformPose: "EPSG:4326" passed to lookupTransform argument target_frame does not exist. 
[component_container_isolated-11] [ERROR] [1718922025.038628823] [controller_server]: Unable to transform robot pose into global plan's frame
[component_container_isolated-11] [WARN] [1718922025.038728945] [controller_server]: [follow_path] [ActionServer] Aborting handle.
```

See https://github.com/open-navigation/opennav_coverage/issues/61 for me details

**Comment by Gonzalo-Mier** [comment]
Hi @MarcM0,

About the problem on UTM, I've realized that you passed `UTM:10N datum: WGS84`. Be aware that spaces produce a format error, so use  `UTM:10N datum:WGS84` instead.  Please, check if that solves the issue.

On the other hand, the `EPSG:4326` error is a ROS error because it cannot find a correct `tf` on the ROS environment (https://answers.ros.org/question/240427/tflookupexception-base_link-passed-to-lookuptransform-argument-target_frame-does-not-exist/). Not sure why `EPSG:4326` is the input to `tf`, but there is nothing f2c could do to solve it.

**Comment by MarcM0** [comment]
Hey, thanks. I had already tried removing the space, but even with UTM:10N datum:WGS84 I get the same 1027 error.

**Comment by Gonzalo-Mier** [comment]
Can you provide a minimal example of your code?

**Comment by MarcM0** [comment]
Thats a bit hard, ive essentially merged the nav2 gps demo https://docs.nav2.org/tutorials/docs/navigation2_with_gps.html with the open_nav coverage demo https://github.com/open-navigation/opennav_coverage/tree/iron/opennav_coverage_demo. Ive also realized it seems this error is related to 10N. If I change my coordinates to elsewhere, say 14N, I get `Internal Fields2Cover error: Geometry does not contain point 0`

**Comment by Gonzalo-Mier** [comment]
Can you check that the transformed Geometry has anything inside? It seems like the new geometry is empty

**Comment by MarcM0** [comment]
Since its within the opennav library, ive decided to just switch to using map frame
