### ISSUE TITLE
undefined reference to `pthread_mutexattr_init@GLIBC_2.34；

### ISSUE THREAD

**Issue by zzzhp000** [Fields2Cover/Fields2Cover#169]
/usr/bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `__libc_single_threaded@GLIBC_2.32'
/usr/bin/ld/usr/bin/ld: : /home/zzz/home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: /home/Fields2Cover/build//_deps/ortools-zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9:src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_init@GLIBC_2.34 '
/undefined reference to usr/bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined` std::__exception_ptr::reference to `pthread_create@GLIBC_2.34'
/usr/bin/ldexception_ptr:: /home/zzz/:Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `__libc_single_threaded@GLIBC_2.32'_M_release()@
/usr/CXXABI_1.3.13bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools'-
/usr/src/bin/ld:lib/ /home/zzzlibortools.so.9:/Fields2Cover/build/ undefined_deps/ortools- referencesrc/lib/ tolibortools.so.9: undefined  `dlclose@GLIBC_2.34'reference
/ to `std::condition_variable::wait(std::unique_lock<usr/bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9:std::mutex> undefined reference to `std::&)@GLIBCXX_3.4.30__exception_ptr:'
/usr:exception_ptr/bin/ld: /::_M_release()@CXXABI_1.3.13'
/usr/bin/ld:home/ /home/zzz/zzz/Fields2Cover/build/_deps/Fields2Coverortools-src/lib/libortools.so.9/:build/_deps/ undefined referenceortools -src/libto `std/::condition_variable::waitlibortools.so.9: undefined (std::unique_lock<stdreference to `pthread_detach@GLIBC_2.34'
::mutex/>&)@GLIBCXX_3.4.30'
/usr/usr/bin/ld: /homebin//zzz/Fields2Cover/buildld: /_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_detach/@GLIBC_2.34'
home//zzz/Fields2Coverusr/bin/ld: //homebuild/_deps//zzzortools-src/lib/Fields2Cover/libortools.so.9: /build/_deps/ortools-src/lib/libortools.so.9: undefinedundefined reference to reference `pthread_key_delete@GLIBC_2.34 to'
/usr/bin/ld: /home `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: //home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9zzz/Fields2Cover/build/_deps/ortools-src/: undefined lib/reference to `std::to_chars(char*, libortools.so.9: undefined reference to `std::to_chars(char*, char*, double)@GLIBCXX_3.4.29'
/usr/bin/ld: /char*home/zzz/,Fields2Cover/build/_deps double)@GLIBCXX_3.4.29'
/usr/bin/ld: /home/zzz/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `dlsym@GLIBC_2.34'
/usr/bin/ld: /home/zzz/Fields2Cover/build/ortools-src/lib/libortools.so.9: /_deps/ortools-src/lib/libortools.so.9: undefined reference to `undefined reference to `pthread_mutex_timedlock@GLIBC_2.34dlsym@GLIBC_2.34'
/usr/bin/ld:'
 /home//usr/bin/ld:zzz/Fields2Cover/build //_deps/ortools-srchome//lib/libortools.so.9: undefined zzz/reference to `pthread_mutex_timedlockFields2Cover/@GLIBC_2.34'
/build/usr/bin/ld: /home_deps/zzz/Fields2Cover//build/_deps/ortools-src/libortools-/libortools.so.9: undefined reference to `pthread_setspecific@GLIBC_2.34src/'
/usr/binlib//ld: /home/zzz/Fields2Coverlibortools.so.9/build/_deps/:ortools undefined reference-src/lib/libortools.so.9:  undefinedto `pthread_setspecific reference@GLIBC_2.34'
 to `/dlopen@GLIBC_2.34'
How to solve this problem？

**Comment by zzzhp000** [comment]
Ubuntu20.04

**Comment by ucmmesa** [comment]
The version of ortools in the CMakeLists.txt is 9.9, but 9.1 maybe work

**Comment by JaMan-cmd** [comment]
Problem solved by building or-tools from source before building F2C

**Comment by Tcoloi** [comment]
> Problem solved by building or-tools from source before building F2C

Bro, how do you managed to solve this problem？I get the same error, though I built  or-tools from source. Did you build or-tools from source by editing the cmake file？
`option(USE_ORTOOLS_FETCH_SRC "Get or-tools from source" OFF)`，should I set this ON？

**Comment by JaMan-cmd** [comment]
No, It was straight forward, I cloned OR-tools from github, installed it with 
`cmake -S . -B build -DBUILD_DEPS=ON &&\
    cmake --build build --config Release --target install -v` then cloned F2C, checked tag v2.0.0 and built it with 
`cmake -DCMAKE_BUILD_TYPE=Release -DUSE_ORTOOLS_RELEASE=ON .. && make -j$(nproc) && make install` which asks to rebuilt ORTOOLS but it doesn't build it again since it finds it already on the system. however, building F2C without OR-tools from source first, fetches the wrong or-tools version and throughs the error above, also switching off the `DUSE_ORTOOLS_RELEASE` through a different error that I don't remember at the moment
