### ISSUE TITLE
f2c-ros1 dynamic reconfigure problem

### ISSUE THREAD

**Issue by ucmmesa** [Fields2Cover/Fields2Cover#171]
I would like to compile the f2c-ros1 version and try the demo, but catkin_make_isolated gives the following error prompt,

File "/home/dell/catkin_wsfield/src/fields2cover_ros/cfg/Controls.cfg", line 13, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import *
ImportError: No module named dynamic_reconfigure.parameter_generator_catkin

However,when I just write a simple dynamic_reconfigure program to publish parameters dynamically,the simple program works.Why the f2c-ros1 gives the error message?

**Comment by Gonzalo-Mier** [comment]
What is f2c-ros1? If you refer to [fields2cover_ros](https://github.com/Fields2Cover/fields2cover_ros), it is not maintained anymore
