### ISSUE TITLE
Void handling in v1.2.1

### ISSUE THREAD

**Issue by Jakubach** [Fields2Cover/Fields2Cover#172]
Hello,
I am using F2C v1.2.1 (in ROS2 Humble) and recently I've noticed a problem with inner fields handling. I use polygons to specify coverage area. In the [F2C graphic](https://fields2cover.github.io/source/tutorials/route_planning.html), the scenario should look like (inner orange and red polygons are skipped):
![image](https://github.com/user-attachments/assets/99d9b01d-e5b6-467d-9d5b-f7f05bbd8078)

Below is the demonstration of the current behavior (the inner polygon is skipped but the planned path is still going through it):

https://github.com/user-attachments/assets/75ab543d-51d9-4b6f-b683-02e9069ba321

Is it actually related to the F2C version and can it be resolved to handle static obstacles or disabled areas inside the covered field? 
Could you advice me with Simple workaround for the v1.2.1 to make it work properly?

**Comment by Gonzalo-Mier** [comment]
Hi @Jakubach,
F2C v2 was released to be able to handle obstacles in the field. The workaround on F2C v1 is to ignore those obstacles or to upgrade the library to v2.

**Comment by 120ccz** [comment]
Hello,
I saw that you said F2C V2 can handle obstacles, and I am currently using F2C V2.0.0 (Humble). Then I found that when running 'path_planning' in tutorials and considering the presence of internal obstacles and using Boustrophedon or SpiralOrder order, the resulting Path does not bypass obstacles (using SnakeOrder order can bypass obstacles), which seems to be the same as the situation in V1 version. May I ask for some advice on handling obstacle areas.
thank you! 

![Image](https://github.com/user-attachments/assets/61a9a337-86d8-4ab1-a8d3-5bd8d38ff228)
![Image](https://github.com/user-attachments/assets/b26247fe-99c4-429e-9314-133b00e64d12)
![Image](https://github.com/user-attachments/assets/759e5e81-95af-48e0-ab57-f01b304f34ef)

**Comment by Jakubach** [comment]
Hi, I had the same issue then I went back again to V1.

**Comment by Jakubach** [comment]
@Gonzalo-Mier Hi, I had the same issue then I went back again to V1.

**Comment by Gonzalo-Mier** [comment]
Hi @120ccz and @Jakubach,
Those fields are not convex. Known patterns, as Boustrophedon or SpiralOrder order, only work in convex fields. For any kind of field, you should use the metaheuristics for route planning: https://fields2cover.github.io/source/tutorials/route_planning.html#metaheuristics-for-route-planning
