### ISSUE TITLE
Any Idea On How to Use Metaheuristics on Large Field?

### ISSUE THREAD

**Issue by ryanxierobo** [Fields2Cover/Fields2Cover#174]
Hi, I am using the library to plan a 3 acre complex shaped field with my DIY robotic mower. So the robot width and cov_width is small: 1m/ 0.7m. 

I tried to use the Metaheuristics route planning for my project, but I found out the code will kill itself if the field is too big.
I wonder are there any ways I can achieve this planning? I tried to use the know pattern it works but since the field is complex, the route will go out of headlands.

Thanks for the help in advance.

This is how I used it:

   # Generate headlands
    hl_generator = f2c.HG_Const_gen()
    mid_hl = hl_generator.generateHeadlands(field, 0.5 * robot.getWidth())
    inside_hl = hl_generator.generateHeadlands(field, 1.0 * robot.getWidth())

    # Generate swaths
    bf = f2c.SG_BruteForce()
    direction = math.pi
    swaths = bf.generateSwaths(direction, robot.getCovWidth(), inside_hl)

    # Generate route
    route_planner = f2c.RP_RoutePlannerBase()
    route = route_planner.genRoute(mid_hl, swaths)  # this is a sorted swaths

    # Generate path
    path_planner = f2c.PP_PathPlanning()
    dubins = f2c.PP_DubinsCurves()
    path_dubins = path_planner.planPath(robot, route, dubins)
    
  I also tried to use C++ but it failed to generate large field also.

**Comment by Gonzalo-Mier** [comment]
Hi @ryanxierobo, welcome to the project!

Your field is not that large and in the range of what we have already tested, so that should not be the problem. Without seeing you field is hard to debug. You mention your field shape is complex. Does that mean you have some corridor that split the field in two (or more), after generating the headlands? An easy test would be to do `mid_hl.size()`. If that is bigger than 1, the error is there. To do more debugging, we would need the field shape.

**Comment by ryanxierobo** [comment]
Hi @Gonzalo-Mier . Thanks for the reply! Love this project!

To provide more context for debugging. Due to the small size of my robot, only about 1m in width. the total number of swaths are quite large(about 600), despite the area is not too big (only about 3 acres, or 12130 square meters). And if I want to use the Metaheuristics sort, it will take very long about 30s for 377 swaths. I tested the code with larger cov_width or smaller fields which all worked fine. 

Here is how the output looks like for a run, I increased the time limits in computeBestRoute to make it run without kill itself:

`python3 path_planner_test.py 
Field creation time: 0.0053 seconds
No-go zones addition time: 0.0000 seconds
mid_hl size: 1
Headlands generation time: 0.0025 seconds
swaths size: 377
Swaths generation time: 0.0148 seconds
Route generation time: 31.2106 seconds
Last path point:  Point(50, 50, 0)
Length of combined points:  115097
Path and boundaries combination time: 0.1420 seconds
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Press ENTER to continue...
`

Here is how my field look like, complex, but no corridors in between:
![image](https://github.com/user-attachments/assets/1b5e0efd-931e-4bf3-ad06-f7cabcf085f6)

**My question will be if there are any parameters in the Metaheuristics route planner code I can tune for to make it faster. Even if it is not shortest path, it should be fine, my most important goal is to get a complete coverage path**

To better debuggin, here is my entire code (modified from the tutorials):
'import math
import fields2cover as f2c
import json
import time

def create_f2c_point(point_tuple):
    return f2c.Point(float(point_tuple[0]), float(point_tuple[1]))

def create_field(field_points):
    if not field_points:
        raise ValueError("Field points list is empty")
    f2c_points = [create_f2c_point(point) for point in field_points]
    if f2c_points[0] != f2c_points[-1]:
        f2c_points.append(f2c_points[0])
    return f2c.Cells(f2c.Cell(f2c.LinearRing(f2c.VectorPoint(f2c_points))))

def add_no_go_zone(field, no_go_points):
    if not no_go_points:
        raise ValueError("No-go zone points list is empty")
    f2c_no_go_points = [create_f2c_point(point) for point in no_go_points]
    if f2c_no_go_points[0] != f2c_no_go_points[-1]:
        f2c_no_go_points.append(f2c_no_go_points[0])
    field.addRing(0, f2c.LinearRing(f2c.VectorPoint(f2c_no_go_points)))

def distance(point1, point2):
    return math.sqrt((point1.X() - point2.X())**2 + (point1.Y() - point2.Y())**2)

def combine_path_and_boundaries(path: f2c.Path, field: f2c.Cells):
    combined_line_string = f2c.LineString()
    
    # Extract path points from path
    path_points = path.toLineString()
    for point in path_points:
        combined_line_string.addPoint(point)
    
    # Get the last point of the path
    last_path_point = path_points.endPoint()
    print("Last path point: ", last_path_point)
    
    # Extract boundary points from field
    boundary_points = list(field.getCell(0).getExteriorRing())
    #print(boundary_points)
    
    # Find the closest boundary point to the last path point
    min_distance = float('inf')
    closest_index = 0
    for i, point in enumerate(boundary_points):
        dist = distance(last_path_point, point)
        if dist < min_distance:
            min_distance = dist
            closest_index = i
    
    # Reorder boundary points starting from the closest point
    reordered_boundary_points = boundary_points[closest_index:] + boundary_points[:closest_index]
    reordered_boundary_points.append(boundary_points[closest_index])
    
    # Add reordered boundary points to the combined line string
    for point in reordered_boundary_points:
        combined_line_string.addPoint(point)
    
    print("Length of combined points: ", combined_line_string.size())
    return combined_line_string

def main():
    start_time = time.time()

    # Set up robot 
    robot = f2c.Robot()
    robot.setWidth(1)  # m
    robot.setCovWidth(0.7)  # m
    robot.setMinTurningRadius(0.2)  # m
    robot.setMaxDiffCurv(0.1)  # 1/m^2

    # Load local coordinates from JSON file
    with open("test_field.json", 'r') as f:
        local_coords = json.load(f)

    # Create field from local coordinates
    field_creation_start = time.time()
    field = create_field(local_coords)
    field_creation_end = time.time()
    print(f"Field creation time: {field_creation_end - field_creation_start:.4f} seconds")

    # Add no-go zones
    no_go_zones_start = time.time()
    #add_no_go_zone(field, [(10, 10), (50, 10), (50, 20), (10, 20)])
    #add_no_go_zone(field, [(-30, -10), (-40, -10), (-40, -20), (-30, -20)])
    #add_no_go_zone(field, [(-50, 0), (-55, 0), (-55, -10), (-50, -10)])
    no_go_zones_end = time.time()
    print(f"No-go zones addition time: {no_go_zones_end - no_go_zones_start:.4f} seconds")

    # Generate headlands
    headlands_start = time.time()
    hl_generator = f2c.HG_Const_gen()
    mid_hl = hl_generator.generateHeadlands(field, 0.25 * robot.getWidth())
    print("mid_hl size:", mid_hl.size())
    inside_hl = hl_generator.generateHeadlands(field, 0.5 * robot.getWidth())
    headlands_end = time.time()
    print(f"Headlands generation time: {headlands_end - headlands_start:.4f} seconds")

    # Generate swaths
    swaths_start = time.time()
    bf = f2c.SG_BruteForce()
    direction = math.radians(0)
    swaths = bf.generateSwaths(direction, robot.getCovWidth(), inside_hl)
    swaths_end = time.time()
    print("swaths size:", swaths[0].size())
    print(f"Swaths generation time: {swaths_end - swaths_start:.4f} seconds")

    # Generate route
    route_start = time.time()
    route_planner = f2c.RP_RoutePlannerBase()
    route_planner.setStartAndEndPoint(f2c.Point(50.0, 50.0))
    route = route_planner.genRoute(mid_hl, swaths)
    #route = route_planner.genSortedSwaths(swaths);
    route_end = time.time()
    print(f"Route generation time: {route_end - route_start:.4f} seconds")

    # Generate path
    path_start = time.time()
    path_planner = f2c.PP_PathPlanning()
    dubins = f2c.PP_DubinsCurves()
    path_dubins = path_planner.planPath(robot, route, dubins)
    path_end = time.time()
    #print(f"Path generation time: {pat  h_end - path_start:.4f} seconds")

    # Combine path and boundaries
    combine_start = time.time()
    complete_path = combine_path_and_boundaries(path_dubins, field)
    combine_end = time.time()
    print(f"Path and boundaries combination time: {combine_end - combine_start:.4f} seconds")

    # Visualization
    f2c.Visualizer.figure()
    f2c.Visualizer.plot(field)
    #f2c.Visualizer.plot(swaths)
    f2c.Visualizer.plot(complete_path)
    f2c.Visualizer.show()


if __name__ == "__main__":
    main()
'


Thank you again for you help and support!

**Comment by Gonzalo-Mier** [comment]
I thought the program was crashing. Have you check if the solution makes sense?

The solver options are set here:
https://github.com/Fields2Cover/Fields2Cover/blob/2e1e43bc483c369091246d3f633609b08207f0a6/src/fields2cover/route_planning/route_planner_base.cpp#L161-L171

Feel free to modify them to obtain a faster solution

**Comment by Gonzalo-Mier** [comment]
As there is no update on this issue, I'll close it. Feel free to open it again if needed.
