### ISSUE TITLE
make a docker environment

### ISSUE THREAD

**Issue by zzm-svg** [Fields2Cover/Fields2Cover#176]
hello,Hello, I would like to ask if I can generate a usable Field2Cover image in an Ubuntu 20.04 environment with your Dockerfile? What dependencies are needed? Or if you have a directly executable image, could you share it?

**Comment by Gonzalo-Mier** [comment]
Hi @zzm-svg,

yes, you can generate the docker image from the Dockerfile in your system. Download the Fields2Cover library and, from the main folder do:

```
docker build -t fields2cover .
docker run -it fields2cover
```

You only need to have docker installed

**Comment by zzm-svg** [comment]
HI,Due to network reasons, I cannot pull osgeo/gdal:ubuntu-full-3.6.3. Can you provide me with a mirror? Thank you very much.

**Comment by vinnnyr** [comment]
what are your network restrictions? the container repo? or the specific image?

**Comment by Gonzalo-Mier** [comment]
As there are no updates, I'll close this issue
