### ISSUE TITLE
Undefined Reference Error During Build of Unit Tests

### ISSUE THREAD

**Issue by gribes02** [Fields2Cover/Fields2Cover#179]
#### **Description**
I encountered a linking error when trying to build the `Fields2Cover` repository from source using `make -j4`. The build process fails at the final stage when linking the unit tests, and the error seems related to the Google Test framework (`gtest`), with several "undefined reference" errors appearing.

I am using the version 1.2.1 
Ubuntu 22.04

#### **Steps to Reproduce**
1. Clone the `Fields2Cover` repository.
2. Install all the aforementioned packages:
```
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get install --no-install-recommends build-essential ca-certificates cmake \
     doxygen g++ git libeigen3-dev libgdal-dev libpython3-dev python3 python3-pip \
     python3-matplotlib python3-tk lcov libgtest-dev libtbb-dev swig libgeos-dev \
     gnuplot libtinyxml2-dev nlohmann-json3-dev
python3 -m pip install gcovr
```

4. Follow the build instructions:
   - `mkdir build && cd build`
   - `cmake -DCMAKE_BUILD_TYPE=Release -DUSE_ORTOOLS_RELEASE=ON ..`
   - `make -j4`
5. The build process fails at 100% when linking the `unittests` executable.

#### **Error Message**
![image](https://github.com/user-attachments/assets/cf8ec353-fa9f-4109-9442-b9fb7d44c3ab)

Would appreciate some help :)

**Comment by Gonzalo-Mier** [comment]
Hi @gribes02,

Is it possible that you cloned fields2cover, compiled it, change the branch to v1.2.1 and then compile it again with those commands? If that is the case, remove the build folder and try to compile it again.

I think that can be the issue because v1.2.1 doesn't have the `boustrophedon_decomp_test.cpp`

**Comment by gribes02** [comment]
Hi @Gonzalo-Mier, thank you for the fast reply!

I removed the Fields2Cover repository and installed the zip file that corresponded with the v1.2.1 version. I also made sure that my `usr/local/include` had no Fields2Cover folders. In the repository I created the `build` repository and compiled again following the previously given steps however I got the same error as you can see. 
![image](https://github.com/user-attachments/assets/08231433-38a7-43f5-a76e-8d081afea088)

**Comment by Gonzalo-Mier** [comment]
Did you check on `/usr/local/lib`? Probably you still have `libFields2Cover.so` there (or something similar)

**Comment by gribes02** [comment]
Yes apologies, I meant to say I checked bin, lib, include and share folders to make sure there was nothing related to Fields2Cover before compiling. Which was not the case. (I am guessing it was not the case as I never managed to run the sudo make install)

**Comment by Gonzalo-Mier** [comment]
It seems that it is not linking well with gtest, but not sure why. Why don't you just use the main version?

**Comment by gribes02** [comment]
Sadly I need the v1.2.1 version in order to work with the opennav_coverage package. Do you think that setting the BUILD_TESTS to OFF in the CMakeLists.txt would cause any problems? I am not really sure what the gtest is testing.

**Comment by Gonzalo-Mier** [comment]
That's also fine. gtest test the library functionalities. You can assume those are fine and set the flag off.

I'll close it. Feel free to re-open if needed
