### ISSUE TITLE
Fields2Cover/src/fields2cover/types/Graph.cpp:69:21: error: ‘remove_if’ is not a member of ‘std’; did you mean ‘remove_cv’?

### ISSUE THREAD

**Issue by TobyTowler** [Fields2Cover/Fields2Cover#182]
Hi, 
I am trying to build the code and getting this error after executing the "make -j$(nproc);" command.
I am on fedora 40 and believe all the dependencies installed, is there anything I can do to make it run?
Thanks

**Comment by Gonzalo-Mier** [comment]
Can you check it again using the last commit? It should be solved now

**Comment by TobyTowler** [comment]
Thanks for the reply, i recloned and instead got this error:
types/Graph.h:18:63: error: ‘int64_t’ was not declared in this scope
I will try running the latest release instead
Thank you

p.s
Thanks ill tell him :)

**Comment by TobyTowler** [comment]
Latest release didnt work:
types/Point.h:92:19: error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]
   92 |   return std::move(OGRPoint(
      |          ~~~~~~~~~^~~~~~~~~~
   93 |       a.getX() + b.getX(),
      |       ~~~~~~~~~~~~~~~~~~~~
   94 |       a.getY() + b.getY(),
      |       ~~~~~~~~~~~~~~~~~~~~
   95 |       a.getZ() + b.getZ()));
      |       ~~~~~~~~~~~~~~~~~~~~~
Thanks

**Comment by Gonzalo-Mier** [comment]
We are not solving bugs from the last release, as they are already solved. On the other hand the bugs you are receiving can be solved with a google search. Can you search those, solve them, and do a PR that solve those issues together?

**Comment by TobyTowler** [comment]
Hi, yea i will give that a go, and lyk
Thanks :)
