### ISSUE TITLE
 Where can I modify the number of generated points in the program?

### ISSUE THREAD

**Issue by cuilongfei1231** [Fields2Cover/Fields2Cover#183]
The path I planned using your program has too many waypoints, and our trajectory tracking program loads slowly. Can I modify the density of the generated points? I hope the spacing between path points can be set. Where can I modify the number of generated points in the program?

**Comment by vinnnyr** [comment]
Yes, you can use `setDiscretization` on the `TurningBase` you pass into your path planner
https://fields2cover.github.io/api/classf2c_1_1pp_1_1TurningBase.html#classf2c_1_1pp_1_1TurningBase

For example (using tutorial https://fields2cover.github.io/source/tutorials/path_planning.html as basis):
```
f2c::Random rand(42);
F2CRobot robot (2.0, 6.0);
f2c::hg::ConstHL const_hl;
F2CCells cells = rand.generateRandField(1e4, 5).getField();
F2CCells no_hl = const_hl.generateHeadlands(cells, 3.0 * robot.getWidth());
f2c::sg::BruteForce bf;
F2CSwaths swaths = bf.generateSwaths(M_PI, robot.getCovWidth(), no_hl.getGeometry(0));
f2c::rp::SnakeOrder snake_sorter;
swaths = snake_sorter.genSortedSwaths(swaths);

robot.setMinTurningRadius(2);  // m
robot.setMaxDiffCurv(0.1);  // 1/m^2
f2c::pp::PathPlanning path_planner;

f2c::pp::DubinsCurves dubins;
dubins.setDiscretization(0.1); // the main thing here to change
F2CPath path_dubins = path_planner.planPath(robot, swaths, dubins);
```

The default discretization is 0.01 m as shown here
https://github.com/Fields2Cover/Fields2Cover/blob/d785d575daf69bb0da70e032d1f11fcd1219db77/include/fields2cover/path_planning/turning_base.h#L92

**Comment by Gonzalo-Mier** [comment]
Thank you @vinnnyr!
