### ISSUE TITLE
 Fields2Cover 2.0 program cannot be successfully compiled on my computer with Ubuntu 20.04

### ISSUE THREAD

**Issue by cuilongfei1231** [Fields2Cover/Fields2Cover#184]
The Fields2Cover 2.0 program cannot be successfully compiled when using Ortools. Could you please guide me on how to compile it,
Sincere thanks to you
thank
Dr. Cui

 The errors during compilation are as follows
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_sigmask@GLIBC_2.32'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_settype@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `stat@GLIBC_2.33'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_once@GLIBC_2.34'
/usr/bin/ld: ../libFields2Cover.so: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_key_create@GLIBC_2.34'
collect2: error: ld returned 1 exit status
make[2]: *** [tutorials/CMakeFiles/6_path_planning_tutorial.dir/build.make:100: tutorials/6_path_planning_tutorial] Error 1
make[1]: *** [CMakeFiles/Makefile2:1254: tutorials/CMakeFiles/6_path_planning_tutorial.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `__libc_single_threaded@GLIBC_2.32'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_detach@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::to_chars(char*, char*, double)@GLIBCXX_3.4.29'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `dlsym@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutex_timedlock@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_setspecific@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `dlopen@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_sigmask@GLIBC_2.32'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_mutexattr_settype@GLIBC_2.34'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `stat@GLIBC_2.33'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_once@GLIBC_2.34'
/usr/bin/ld: ../libFields2Cover.so: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /home/iqr/Fields2Cover-main(1)/Fields2Cover-main/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_key_create@GLIBC_2.34'
collect2: error: ld returned 1 exit status
make[2]: *** [tutorials/CMakeFiles/4_swath_generator_tutorial.dir/build.make:100: tutorials/4_swath_generator_tutorial] Error 1

![image](https://github.com/user-attachments/assets/33493872-abe6-47cc-9f4c-817299e8caa0)

**Comment by Gonzalo-Mier** [comment]
Hi @cuilongfei1231,

Not sure if you used any parameters when you compiled it. Can you try to remove the build folder and compile it again with  `cmake -DUSE_ORTOOLS_RELEASE=ON ..`?
