### ISSUE TITLE
How to generate holes in field

### ISSUE THREAD

**Issue by TobyTowler** [Fields2Cover/Fields2Cover#189]
How to generate a field with holes in it? as seen in the docs?
![image](https://github.com/user-attachments/assets/cf9d4cf8-9e5f-4c77-803e-8179296084af)

thanks

**Comment by Gonzalo-Mier** [comment]
Hi @TobyTowler,

You can check the tutorials of how it was done:
https://github.com/Fields2Cover/Fields2Cover/blob/main/tutorials/5_route_planning.cpp
https://github.com/Fields2Cover/Fields2Cover/blob/main/tutorials/python/5_route_planning.py

https://github.com/Fields2Cover/Fields2Cover/blob/1d417de070d53cee163829000000414d3c60887c/tutorials/5_route_planning.cpp#L16-L26

**Comment by TobyTowler** [comment]
Thank you sorry i didnt check that peice of code
