### ISSUE TITLE
Create some blog posts about the library

### ISSUE THREAD

**Issue by Gonzalo-Mier** [Fields2Cover/Fields2Cover#24]
To help others to use the library, it would be great to create some blog posts using the library. 

Please, append the link to those blog posts to the [blog_posts.md](https://github.com/Fields2Cover/Fields2Cover/blob/main/blog_posts.md) file.

Thank you.

**Comment by chiragkhatri19** [comment]
Can I work on this ?

**Comment by Gonzalo-Mier** [comment]
Of course, and thanks for participating.
