### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by jfulem** [Fields2Cover/Fields2Cover#3]
Hi, great work! I’d like to ask whether you are planning any interface to python or any python wrapper?

**Comment by Gonzalo-Mier** [comment]
Hi @jfulem, right now I'm writing two papers for some conferences, and then holidays, so until August/September I would say. Either way, I will push the python wrapper I have now (not completely functional) with SWIG to a different branch, so anyone can improve it if they want.

Thanks for your interest.

**Comment by Gonzalo-Mier** [comment]
Hi @jfulem,

There is a new branch called _python_interface_

Swig can be installed as `sudo apt install swig`
To compile the project with swig from the build folder: `cmake -DBUILD_SWIG=ON ..; make`
To install the python library from the build folder:
```
cd swig/python
sudo python setup.py install
```
And from that point you can use the library in python as `import fields2cover`. I was translating the tutorials from c++ to python, but many bugs appeared. A complete example of a normal flow with fields2cover in python is in the file [tutorials/python/6_path_planning.py](https://github.com/Fields2Cover/Fields2Cover/blob/python_interface/tutorials/python/6_path_planning.py)

Thank you

**Comment by jfulem** [comment]
I tested it. It all works fine. It's great.

**Comment by jfulem** [comment]
Hi @Gonzalo-Mier, is it possible to plan the dubins path for more than 1 robot (machine) on one field? If so, please, can you send me some hints. Thanks a lot!

**Comment by vectorcrumb** [comment]
Hi, with respect to the plural types that use `std::initializer_list` in their constructor (like Swaths, LinearRing and LineString), could a alternative constructor using a datatype such as `std::vector` be implemented? That's the recomendation found [here](https://www.swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_initializer_lists) in the SWIG docs.

**Comment by Gonzalo-Mier** [comment]
> Hi @Gonzalo-Mier, is it possible to plan the dubins paths for more than 1 robot (machine) on one field? If so, please, can you send me some hints. Thanks a lot!

I have opened a new issue to discuss it.

> Hi, with respect to the plural types that use std::initializer_list in their constructor (like Swaths, LinearRing and LineString), could a alternative constructor using a datatype such as std::vector be implemented? That's the recomendation found [here](https://www.swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_initializer_lists) in the SWIG docs.

Thank you @vectorcrumb. There are many things that could improve the python interface. We are open to PR :)

**Comment by marliesdekeizer** [comment]
As it works for both of you it probably has something to do with my settings, but I get an error on running 6_path_planning.py:

####### Tutorial 6.1 Dubins curves ######
double free or corruption (out)
Aborted

It goes wrong in _fields2cover_python.PathPlanning_searchBestPath(self, swaths, turn) but I don't know why. Have you experienced this?

**Comment by jfulem** [comment]
@marliesdekeizer, this works just fine.

**Comment by Gonzalo-Mier** [comment]
> As it works for both of you it probably has something to do with my settings, but I get an error on running 6_path_planning.py:
> 
> ####### Tutorial 6.1 Dubins curves ###### double free or corruption (out) Aborted
> 
> It goes wrong in _fields2cover_python.PathPlanning_searchBestPath(self, swaths, turn) but I don't know why. Have you experienced this?

Hi @marliesdekeizer, once you have compiled it (from build folder: `cmake -DBUILD_SWIG=ON ..; make`), could you try to do
`make check`?

Tell me if you receive the same problem. Let's see if we can solve it :) Thank you for your interest.

**Comment by marliesdekeizer** [comment]
Thanx for responding so fast.

During the build I get a few warnings: 

`
Scanning dependencies of target xmltest
[ 50%] Building CXX object _deps/tinyxml2-build/CMakeFiles/xmltest.dir/xmltest.cpp.o
/home/marliesdekeizer/git_projects/Fields2Cover/build/_deps/tinyxml2-src/xmltest.cpp: In function ‘int main(int, const char**)’:
/home/marliesdekeizer/git_projects/Fields2Cover/build/_deps/tinyxml2-src/xmltest.cpp:711:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  711 |     fgets( savedBuf, 256, saved );
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/marliesdekeizer/git_projects/Fields2Cover/build/_deps/tinyxml2-src/xmltest.cpp:1195:9: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
 1195 |    fgets( buf, 1024, textfile );
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
[ 51%] Linking CXX executable xmltest
[ 51%] Built target xmltest
`

`[ 98%] Swig compile ../Fields2Cover.i for python
/home/marliesdekeizer/git_projects/Fields2Cover/swig/python/../../include/fields2cover/types/Swaths.h:45: Warning 389: operator[] ignored (consider using %extend)
/home/marliesdekeizer/git_projects/Fields2Cover/swig/python/../../include/fields2cover/types/Swaths.h:47: Warning 389: operator[] ignored (consider using %extend)
[ 98%] Built target fields2cover_python_swig_compilation
`

And with make check I get an error:
`2: [  FAILED  ] 1 test, listed below:
2: [  FAILED  ] fields2cover_hl_const_gen.empty_area
2: 
2:  1 FAILED TEST
2: free(): invalid pointer
2/2 Test #2: unittests ........................Child aborted***Exception: 135.39 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) = 135.49 sec

The following tests FAILED:
          2 - unittests (Child aborted)
Errors while running CTest
make[3]: *** [CMakeFiles/check.dir/build.make:57: CMakeFiles/check] Error 8
make[2]: *** [CMakeFiles/Makefile2:304: CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:311: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:197: check] Error 2`

**Comment by Gonzalo-Mier** [comment]
First warning comes from the tinyxml2 library, which we cannot solve from here.
Second warning will be solved soon, but it doesn't affect this problem.

I have two things to ask:
- Could you run it with privileges as `sudo make check`? (I don't know if you can)
- Could you remove the build folder, create it again and send us the report of `cmake -DBUILD_SWIG=ON ..`

Thank you for your time

**Comment by marliesdekeizer** [comment]
Using sudo gives the same result for make check

I have rebuilt it, using a different version of python. I used the Anaconda version before, so I thought I'll try it 'as clean as possible'. The report is:
`-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using the single-header code from /home/marliesdekeizer/git_projects/Fields2Cover/build/_deps/json-src/single_include/
-- The C compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter Development 
-- Found Python3: /usr/lib/python3/dist-packages/numpy/core/include (found version "3.8.10") found components: NumPy Interpreter Development 
-- Found GDAL: /usr/lib/libgdal.so (found suitable version "3.3.2", minimum required is "2.0") 
-- Found SWIG: /usr/bin/swig4.0 (found version "4.0.1") 
-- Found Python: /home/marliesdekeizer/.vscode-server/data/User/globalStorage/donjayamanne.python-environment-manager/symlinksV1/python_a304198fa501aed78c624fff01c9031acfdbd78cd238e4e23ea00a28a70e1b02af57b949f568a6ca5e92570c2db21e5857ea9aa68a8feda1e33bf1393575ce61/python (found version "3.8.10") found components: Interpreter Development 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marliesdekeizer/git_projects/Fields2Cover/build`

When I then run `sudo python setup.py install` I get the following error:
`/usr/lib/python3/dist-packages/setuptools/dist.py:473: UserWarning: Normalizing '1.0.1-dev' to '1.0.1.dev0'
  warnings.warn(
running install
error: [Errno 2] No such file or directory: '/home/marliesdekeizer/git_projects/Fields2Cover/build/swig/python/fields2cover.py'`

**Comment by Gonzalo-Mier** [comment]
The last error you had is because after `cmake -DBUILD_SWIG=ON ..`, you have to do `make` again. Then move to `cd swig/python`, and finally `sudo python setup.py install`.

About your main error, the configuration seems to be okay. I cannot replicate your error. If you have time to debug it, or can give us more details about the error, it will be a great help.

**Comment by marliesdekeizer** [comment]
Sorry for my earlier reply, I realized too late that I forgot the make.

I do have time to debug, but I'm not familiar with the 'python-c++' combination and how to debug that.

**Comment by Gonzalo-Mier** [comment]
Thank you @marliesdekeizer. I was able to find the issue and with the last commit in the `python_interface` branch should be solved. Please, try it and tell me if the error continues.

PD: I have seen you have removed one of your comments with the cmake information. Once the issue is solved, please, leave the error message just in case someone find the same error in the future. Thank you for your time :)

**Comment by marliesdekeizer** [comment]
Thanx so much! I will try it and let you know.

P.S. I removed the comment because it was the one where I forgot the make. So I was a bit ashamed and I thought it wasn't useful :-)

**Comment by marliesdekeizer** [comment]
Works like a charm!! Thank you for the quick response!

**Comment by Gonzalo-Mier** [comment]
I'm almost finished with the python interface. Before September we will have a completely functional python library with their tests :)

**Comment by jfulem** [comment]
I definitely will do that. Thanks!

**Comment by Gonzalo-Mier** [comment]
Python interface is done. You can check how to use it in the tutorials folder. I'll update the documentation, and then do a PR.

To compile and install the library with python, you have to:
`cmake -DBUILD_PYTHON=ON ..; sudo make install`

Note that the flag to compile the python interface has changed from BUILD_SWIG to BUILD_PYTHON. 
The intallation method is also simplified. `sudo make install` installs the C++ and the Python library, so no more actions are required.

**Comment by jfulem** [comment]
You have added some functions from the `Transform` class, which is great. This looks very good. I'm testing it now, so far no issues.

**Comment by Gonzalo-Mier** [comment]
I saw your PR with your comment, but you closed it too early. If you plan to use it, I have no other reason to not add it. 
Thanks for your implication!! :relaxed:

**Comment by marliesdekeizer** [comment]
Thanks!!! It works right away. Great library!
