### ISSUE TITLE
Documentation: Installation instructions

### ISSUE THREAD

**Issue by helvete** [Fields2Cover/Fields2Cover#32]
Hello everyone!

I was about to try this library. So I followed the installation instructions mentioned [here](https://fields2cover.github.io/source/installation.html) and [here](https://github.com/Fields2Cover/Fields2Cover#installation).

In the end I was able to compile it and test it using python import way - yes, I am going through the python path on Ubuntu.

I am creating this issue because the installation instructions are not complete and one has to tweak them at several places.

The points specifically:

1. Ubuntu 20.04 doesn't have `add-apt-repository` installed by default. At least not in all the flavours available. And since it is utilized just at the start in order to be able to install `gis` one has to either install it beforehand or do the repository addition manually as a whole. In short, it suffices to prepend a snippet like this:
```
apt-get -y update && apt-get install -y --no-install-recommends software-properties-common
```

2. Several key dependencies are missing by default and ought to be explicitly installed. I am talking about these: `swig` and `libtbb-dev`. It suffices to append them to the existitng `apt-get install` call

3. In case python2 is not installed, there is no `python` alias or symlink for `python3`, again at least not in all ubuntu flavours. Can be fixed by creating a symlink:
```
ln -s /usr/bin/python3 /usr/bin/python
```

The process I had to do is documented [here](https://github.com/helvete/f2c_poc/blob/32aa82691bedf832f12880cc3a778226d6a7e683/.docker/Dockerfile).

**Comment by Gonzalo-Mier** [comment]
Perfect, thanks for your contribution!

**Comment by helvete** [comment]
Glad to be able to help :wink:
