### ISSUE TITLE
Apple Arm -- Dockerfile build errors

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#34]
Having the following build error in a container generated from the repo Dockerfile

```
In file included from /workspace/fields2cover/include/fields2cover/types/Geometry.h:120,
                 from /workspace/fields2cover/include/fields2cover/types/Point.h:17,
                 from /workspace/fields2cover/include/fields2cover/types.h:15,
                 from /workspace/fields2cover/include/fields2cover/headland_generator/constant_headland.h:11,
                 from /workspace/fields2cover/src/fields2cover/headland_generator/constant_headland.cpp:8:
/workspace/fields2cover/include/fields2cover/types/Geometry_impl.hpp: In instantiation of 'std::string f2c::types::Geometry<T, R>::exportToWkt() const [with T = OGRMultiPolygon; OGRwkbGeometryType R = wkbMultiPolygon; std::string = std::__cxx11::basic_string<char>]':
/workspace/fields2cover/include/fields2cover/types/Geometries_impl.hpp:21:3:   required from 'SAMETYPE f2c::types::Geometries<SAMETYPE, T, R, CHILDRENTYPE>::clone() const [with SAMETYPE = f2c::types::Cells; T = OGRMultiPolygon; OGRwkbGeometryType R = wkbMultiPolygon; CHILDRENTYPE = f2c::types::Cell]'
/workspace/fields2cover/src/fields2cover/headland_generator/constant_headland.cpp:14:36:   required from here
/workspace/fields2cover/include/fields2cover/types/Geometry_impl.hpp:206:28: error: no matching function for call to 'OGRMultiPolygon::exportToWkt()'
  206 |   return data->exportToWkt();
```

I looked  at GDAL api documentation, and it seem like that is a valid function call, so I am unsure what is going on 🤔 
https://gdal.org/api/ogrgeometry_cpp.html#_CPPv4NK15OGRMultiPolygon11exportToWktERK13OGRWktOptionsP6OGRErr

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr,
Thanks to point to this and welcome!! I was not able to reproduce exactly your issue but I believe it's another previous error that leaked here. I've updated the Dockerfile. Now you should be able to build the docker container with C++ and Python interface.
Please, tell me if that solves the issue.

**Comment by vinnnyr** [comment]
@Gonzalo-Mier  OK thanks for the attempted correction.

Even after the fix, I am still having trouble but I think I narrowed it down.

On an x86 machine I am not having that issue, but on an arm machine I am having the same issue, even when on the latest commit.

Does it have to do with the version of `libgdal-dev` on the apt repo? On arm, the apt repo is on `libgdal-dev 3.0.4` where as on x86 I am on `libgdal-dev 3.3.2` .

Perhaps there is a need to find alternate gdal binaries with newer versions, or maybe build gdal from source?

**Comment by Gonzalo-Mier** [comment]
It's weird because the function you point is there since GDAL 2.0, but it's a good try. I tried to install GDAL from source and wasn't able to do it. If we find a better way to install GDAL (also on mac and windows), it would be awesome

**Comment by vinnnyr** [comment]
I'll take a look when I have another chance. I think there might be an ubuntu container that already has GDAL built from source published by them. It might be useful to use that as the base image.

**Comment by vinnnyr** [comment]
I can confirm this is an apple arm v.s. x86 issue. 

On Apple Arm I did this to virtualize x86 and it worked fine off of `main`
`docker build --platform linux/amd64 . --tag fields2cover`

I do not think I have interest in getting it to work on apple arm natively any further --  Should we close this issue, or keep it open for reference?

**Comment by Gonzalo-Mier** [comment]
Perfect, thank you again.
