### ISSUE TITLE
roslaunch error 

### ISSUE THREAD

**Issue by MrDragon2** [Fields2Cover/Fields2Cover#39]
Hello Author ,  When I run "roslaunch", the terminal reports the following error: 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  File not found
 What is the reason?

**Comment by MrDragon2** [comment]
When viewing the node information " rosnode info /visualizer ", I found the following error:

**Comment by MrDragon2** [comment]
When viewing the node information, I found the following error:
Node [/visualizer]
Publications: 
 * /field/border [geometry_msgs/PolygonStamped]
 * /field/no_headlands [geometry_msgs/PolygonStamped]
 * /field/swaths [visualization_msgs/Marker]
 * /gps/fix [sensor_msgs/NavSatFix]
 * /rosout [rosgraph_msgs/Log]
Subscriptions: None
Services: 
 * /visualizer/get_loggers
 * /visualizer/set_logger_level
contacting node http://lgg:40927/ ...
ERROR: Communication with node[http://lgg:40927/] failed!

**Comment by Gonzalo-Mier** [comment]
Related to [https://github.com/Fields2Cover/fields2cover_ros/issues/2](https://github.com/Fields2Cover/fields2cover_ros/issues/2)
