### ISSUE TITLE
pytest-3 error

### ISSUE THREAD

**Issue by MrDragon2** [Fields2Cover/Fields2Cover#40]
Hi author,  after I run "pytest-3", many errors like the following occur !

______________________________ ERROR collecting tests/python/import_f2c_test.py _______________________________
ImportError while importing test module '/home/lgg/Fields2Cover/tests/python/import_f2c_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/python/import_f2c_test.py:9: in <module>
    import fields2cover as f2c
E   ModuleNotFoundError: No module named 'fields2cover'

**Comment by MrDragon2** [comment]
I completed the compilation in ubuntu18.04, and Field2Cover was also successfully compiled .

**Comment by Gonzalo-Mier** [comment]
Hi. Did you compile it with `cmake -DBUILD_PYTHON=ON ..`? after compiling it, did you install the library with `make install`? The error you show it's because the library was not successfully installed.

**Comment by MrDragon2** [comment]
> Hi. Did you compile it with `cmake -DBUILD_PYTHON=ON ..`? after compiling it, did you install the library with `make install`? The error you show it's because the library was not successfully installed.

"Field2Cover" has been successfully installed. The problem is that running with "C++" also reports an error.

**Comment by Gonzalo-Mier** [comment]
Fields2Cover is a C++ library, which also provide a python interface. If the C++ part is not working, the python bridge would not work. Which problem do you have?

**Comment by MrDragon2** [comment]
> Fields2Cover is a C++ library, which also provide a python interface. If the C++ part is not working, the python bridge would not work. Which problem do you have?

I ran "make" and "make install" successfully. Why do I report an error when I run the files directly in "c++".

**Comment by Gonzalo-Mier** [comment]
I don't understand. Can you explain step by step how you find those errors and how do they look like?

**Comment by MrDragon2** [comment]
> I don't understand. Can you explain step by step how you find those errors and how do they look like?

I used to report errors because of "field_ros". Now I want to test whether "Field2Cover" runs normally. Now I find that "c++" and "python" cannot run, but "Field2Cover" has been successfully compiled and installed on the computer, and "GDAL" has also been installed. I don't understand why compilation and installation are successful, and running "g++" and "pytest-3" will still cause errors

**Comment by Gonzalo-Mier** [comment]
> running "g++"

What are you using g++ for? Test on c++ are run with `make check`

**Comment by Gonzalo-Mier** [comment]
I close the actual error was not especified. Feel free to open it again if needed.
