### ISSUE TITLE
Support for overlapping paths

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#41]
Currently overlapping paths are not supported:

From the paper
> In the current version, the library only supports parallel non-overlapping swaths.

What would it take to implement overlaps of constant width? Where would be the best place to insert it (I imagine it is in the swath generation step).

**Comment by Gonzalo-Mier** [comment]
Yes, in this function:
https://github.com/Fields2Cover/Fields2Cover/blob/2fa250253dd2852509b9cf12b84dbc88a49c9c1d/include/fields2cover/swath_generator/swath_generator_base.h#L31

I need to split the heuristic that search the best angle and the swath generator actually. As a way to solve your issue with the current code, you can use a `F2CRobot` with a narrow width and then change the width of the swaths manually.

Just for curiosity, which is the purpouse of re-covering the same area systematically?

**Comment by Gonzalo-Mier** [comment]
> I suspect if I do that, on the edge of the boundary the robot will overhang / violate the boundary right?

The swath generator assume that you have headlands on the sides of the field. So even if the swaths go out of the mainland, you cover part of the headlands (without going outside). 

https://github.com/Fields2Cover/Fields2Cover/blob/2fa250253dd2852509b9cf12b84dbc88a49c9c1d/include/fields2cover/swath_generator/swath_generator_base_impl.hpp#L40-L50

As you can see, no checks are made if the area of the swaths go out of boundaries.


> I am not sure what you mean / how that would help. Can you please clarify?

You can change the width of a swath with this function:

https://github.com/Fields2Cover/Fields2Cover/blob/2fa250253dd2852509b9cf12b84dbc88a49c9c1d/include/fields2cover/types/Swath.h#L45

As F2CSwaths are containers of F2CSwath, you need to create a loop to change the width of each swath.


Other (easier) option is to modify the code on:

https://github.com/Fields2Cover/Fields2Cover/blob/2fa250253dd2852509b9cf12b84dbc88a49c9c1d/include/fields2cover/swath_generator/swath_generator_base_impl.hpp#L40-L50

to:
```
float safe_perc = 0.1; // 10%

int n_swaths {static_cast<int>(ceil(field_width / (op_width - safe_perc)))}; 
auto seed_curve = rot_poly.getStraightLongCurve( 
    F2CPoint(rot_poly.getDimMinX(), rot_poly.getDimMinY()), 
    boost::math::constants::half_pi<double>()); 
  
F2CSwaths swaths; 
for (int i = 0; i < n_swaths; ++i) { 
   auto path = F2CPoint(0.0, 0.0).rotateFromPoint(-angle, 
       seed_curve + F2CPoint(safe_perc / 2, 0.0) + F2CPoint(op_width - safe_perc, 0.0) * (i + 0.5)); 
   swaths.append(path, poly, op_width); 
 } 
```

**Comment by vinnnyr** [comment]
Thanks for the insight @Gonzalo-Mier . I think I will probably test this out and PR the overlap input into the swath generator within the next few months. I will write it here in the issue when I get started.

> As you can see, no checks are made if the area of the swaths go out of boundaries.
Yes I noticed that !  Is there a particular reason? It would be nice to have some sort of way to tell the system "never let the machine violate this boundary" for all types of generators (Swath Generator, Route Planner, Path Planner)

(Maybe this should be filed a separate issue / request)

**Comment by Gonzalo-Mier** [comment]
>     Yes I noticed that ! Is there a particular reason? It would be nice to have some sort of way to tell the system "never let the machine violate this boundary" for all types of generators (Swath Generator, Route Planner, Path Planner)

The reasons is that we assume the headland generator part is used, and right now only constant width headland is provided. Boundaries are actually a huge constraint and we are also working on that part for future releases, but not solved yet.

**Comment by Gonzalo-Mier** [comment]
This option can be handled making the coverage width of the robot smaller than its width. Imagine that the robot has a width of 2m. We can do `F2CRobot robot(2, 1.9)` to have  some overlapping in the path
