### ISSUE TITLE
Robot Start Point

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#42]
When trying to set the robot start point I get a TypeError.
This probably has to do with how std::optional is handled in the cpp to python workflow.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [15], line 49
     45 print(max_x)
     46 print(max_y)
---> 49 robot.start_point = f2c.Point(max_x, max_y)

TypeError: in method 'Robot_start_point_set', argument 2 of type 'std::optional< f2c::types::Point > *'
```

Based on the (cpp) API docs, I expect to be able to set the robot start point.
https://fields2cover.github.io/api/structf2c_1_1types_1_1Robot.html#exhale-struct-structf2c-1-1types-1-1robot

**Comment by Gonzalo-Mier** [comment]
That part is not used right now. Either way, for the record, you can set it as:

```
robot.start_point = f2c.optional_Point(f2c.Point(max_x, max_y))
```
The interface can be definitively better. Something to improve :)

**Comment by Gonzalo-Mier** [comment]
Working on. The route planner module right now are only patterns. However, the idea is to use metaheuristics to find the best pattern. The best pattern includes going from the start point to the first swath, going from the end swath to the end point, plan to refill or empty the tank on the right moment, avoid big slopes to save energy, etc...
