### ISSUE TITLE
How to run Fields2Cover ?

### ISSUE THREAD

**Issue by xluo6688** [Fields2Cover/Fields2Cover#45]
Hello, 

After install Fields2Cover (Ubuntu 20.04),  and import fields2cover successfully. I tried to run this project with 
` pytest tests/python/`, I can see a small window come out but disappeared quickly. My question is: is it correct way to run this project, so the path planning animation can be seen graphically as shown in the project's Readme? Or how to run this project to see the path planning graphically?

Thanks,

**Comment by Gonzalo-Mier** [comment]
Hi @xluo6688,
`pytest` is only used to check the correct behavior of the library. If you want to try the library by yourself, open a python terminal and follow any [tutorial](https://fields2cover.github.io/source/tutorials.html#python-tutorials).

A good example you can try is:
```
import fields2cover as f2c

rand = f2c.Random(42)
robot = f2c.Robot(2.0, 6.0)
robot.setMinRadius(2)  # m
robot.linear_curv_change = 0.1  # 1/m^2

const_hl = f2c.HG_Const_gen()
field = rand.generateRandField(5, 1e4)
cells = field.field
no_hl = const_hl.generateHeadlands(cells, 3.0 * robot.robot_width)
bf = f2c.SG_BruteForce()
swaths = bf.generateSwaths(math.pi, robot.op_width, no_hl.getGeometry(0))
snake_sorter = f2c.RP_Snake()
swaths = snake_sorter.genSortedSwaths(swaths)
path_planner = f2c.PP_PathPlanning()
dubins_cc = f2c.PP_DubinsCurvesCC();
path_dubins_cc = path_planner.searchBestPath(robot, swaths, dubins_cc);

f2c.Visualizer.figure();
f2c.Visualizer.plot(cells);
f2c.Visualizer.plot(no_hl);
f2c.Visualizer.plot(path_dubins_cc);
f2c.Visualizer.plot(swaths);
f2c.Visualizer.show();
```

This code is extracted from [here](https://github.com/Fields2Cover/Fields2Cover/blob/main/tutorials/python/6_path_planning.py). All the code used on the tutorials is in that folder.
