### ISSUE TITLE
Unit test `utm: Invalid value for zone`

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#46]
When running the unittests, we get this

```
ERROR 1: PROJ: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
[1]    639469 segmentation fault (core dumped)  ./unittests
```

This also shows up in CI::
https://github.com/Fields2Cover/Fields2Cover/actions/runs/3878297725/jobs/6614315331

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr,
I'm not able to replicate it on my computer, docker (building the Dockerfile of the repo) nor codespace. 
I've seen that GDAL version on the log is 3.4.3. Is it the same as yours? Any tip to replicate the error?

**Comment by vinnnyr** [comment]
oh, is the CI not set to use the Dockerfile? I guess I didn't realize that. Let me see if I can replicate in the Dockerfile.

**Comment by vinnnyr** [comment]
In CI the verision is 3.5.2
https://github.com/Fields2Cover/Fields2Cover/blob/eabc182286311e5fa3bc6c053c020d0e0774cfb0/.github/workflows/build.yml#L91

**Comment by vinnnyr** [comment]
You are right -- I cannot recreate off of `main` in the Dockerfile
```
docker build . -t f2c && docker run -it f2c ./tests/unittests 
```

What do you think about moving CI to the dockerfile? I can file a new issue for that if you want

**Comment by Gonzalo-Mier** [comment]
Solved on https://github.com/Fields2Cover/Fields2Cover/pull/50
