### ISSUE TITLE
Plan the dubins paths for more than 1 robot (machine) on one field?

### ISSUE THREAD

**Issue by Gonzalo-Mier** [Fields2Cover/Fields2Cover#5]
Hi @Gonzalo-Mier, is it possible to plan the dubins paths for more than 1 robot (machine) on one field? If so, please, can you send me some hints. Thanks a lot!

_Originally posted by @jfulem in https://github.com/Fields2Cover/Fields2Cover/issues/3#issuecomment-1179803236_

**Comment by Gonzalo-Mier** [comment]
Yes, there are 3 ways to do it. I'm going to use 2 robots for the examples.

1. Split the field first, and cover each piece with one robot. 
    Headland gen --> Split --> Robot 1 --> Swath gen --> Route planning --> Path planning --> Path 1
   ___________________|->Robot 2 --> Swath gen --> Route planning --> Path planning --> Path 2
2. Generate the swaths, and then distribute them between robots
    Headland gen --> Split --> Swath gen --> Robot 1 --> Route planning --> Path planning --> Path 1
   _______________________________|->Robot 2 --> Route planning --> Path planning --> Path 2
3.  Distribute the swaths after the route planning.
    Headland gen --> Split --> Swath gen --> Route planning --> Robot 1 --> Path planning --> Path 1
   ______________________________________________|->Robot 2 --> Path planning --> Path 2

Just check if there is a robot doing the turn before other robot start a new turn that could collide with it. Waiting is a good strategy to avoid collisions.

**Comment by jfulem** [comment]
Thank you very much for your answer. I will try.
