### ISSUE TITLE
odd turns when attempting to generate dubins paths

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#64]
I am working with some custom swath generation to work with a field shape that is of interest to us. 

![image](https://user-images.githubusercontent.com/22486686/232153160-2cc41511-d00e-42dd-a435-2bfd9f480e73.png)

And when generating curves, I am getting really odd curves from these sorted swaths at the top, but not at the bottom.
![image](https://user-images.githubusercontent.com/22486686/232155639-590efa0a-1ec1-4669-8b1a-24d836494e52.png)

I know I am not providing much detail right now, but are there some general things I might want to look at in terms of this behavior?

I am just not really sure why the turns at one end double back on themselves yet.
![image](https://user-images.githubusercontent.com/22486686/232155902-06ca5b7d-031f-40fe-b0ce-588a24c8e75a.png)

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr,
Check the size of your F2CSwaths. I have the feeling that for each swath you are generating 2 F2CSwath in opposite directions. So the robot goes to one end and turns there to come back.

**Comment by vinnnyr** [comment]
Yes I was :face_exhaling:  Thanks so much for helping me catch that!

**Comment by Gonzalo-Mier** [comment]
Btw, cool job. That seems impressive :)
