### ISSUE TITLE
catkin_make_isolated error

### ISSUE THREAD

**Issue by RamanaBotta** [Fields2Cover/Fields2Cover#66]
`catkin_make_isolated` 
Base path: /home/boson/nvme0n1p1/catkin_f2c
Source space: /home/boson/nvme0n1p1/catkin_f2c/src
Build space: /home/boson/nvme0n1p1/catkin_f2c/build_isolated
Devel space: /home/boson/nvme0n1p1/catkin_f2c/devel_isolated
Install space: /home/boson/nvme0n1p1/catkin_f2c/install_isolated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~  traversing 2 packages in topological order:
~~  - fields2cover (plain cmake)
~~  - fields2cover_ros
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

==> Processing plain cmake package: 'fields2cover'
==> cmake /home/boson/nvme0n1p1/catkin_f2c/src/fields2coverpath_boson/fields2cover -DCMAKE_INSTALL_PREFIX=/home/boson/nvme0n1p1/catkin_f2c/devel_isolated/fields2cover -G Unix Makefiles in '/home/boson/nvme0n1p1/catkin_f2c/build_isolated/fields2cover/devel'
-- Using the single-header code from /home/boson/nvme0n1p1/catkin_f2c/build_isolated/fields2cover/devel/_deps/json-src/single_include/
**CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Python3 (missing: Python3_LIBRARIES Python3_INCLUDE_DIRS
  Development) (found version "3.9.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
  /usr/share/cmake-3.16/Modules/FindPython3.cmake:300 (include)
  /home/boson/nvme0n1p1/catkin_f2c/build_isolated/fields2cover/devel/_deps/matplotlib_cpp-src/CMakeLists.txt:31 (find_package)**

-- Configuring incomplete, errors occurred!
See also "/home/boson/nvme0n1p1/catkin_f2c/build_isolated/fields2cover/devel/CMakeFiles/CMakeOutput.log".
<== Failed to process package 'fields2cover': 
  Command '['cmake', '/home/boson/nvme0n1p1/catkin_f2c/src/fields2coverpath_boson/fields2cover', '-DCMAKE_INSTALL_PREFIX=/home/boson/nvme0n1p1/catkin_f2c/devel_isolated/fields2cover', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/boson/nvme0n1p1/catkin_f2c/build_isolated/fields2cover && cmake /home/boson/nvme0n1p1/catkin_f2c/src/fields2coverpath_boson/fields2cover -DCMAKE_INSTALL_PREFIX=/home/boson/nvme0n1p1/catkin_f2c/devel_isolated/fields2cover -G 'Unix Makefiles'

Command failed, exiting.

Hi @Gonzalo-Mier Can you please help us solve this error please?

**Comment by Botronics** [comment]
@Gonzalo-Mier Even though followed all the instruction given in the readme file still we are getting  the error

**Comment by Botronics** [comment]
> Could you try to `sudo apt-get install python3-dev`?

@Gonzalo-Mier I already tried that.

**Comment by Gonzalo-Mier** [comment]
I wasn't able to reproduce it. If you can create a docker with your problem, it would be easier for me to debug.

**Comment by Botronics** [comment]
@Gonzalo-Mier  yeah sure. i am using Nvidia Jetson-AGX and ubuntu version is Ubuntu 20.04.5 LTS (Focal Fossa).ROS  noetic version

**Comment by JensOgorek** [comment]
@RamanaBotta Also had problems with catkin_make_isolated inside a docker. Switched over to catkin build and it worked.

**Comment by Gonzalo-Mier** [comment]
@JensOgorek Can you provide the docker file?

**Comment by JensOgorek** [comment]
> @JensOgorek Can you provide the docker file?

Sure, I use docker compose and an entry point. I just took my baseline docker file for ROS2 and changed it until it worked :)

Also, the visuals are configured for Ubuntu with X11. 


<details><summary>Code</summary>

To actually view RVIZ and rqt you also have to config xhost in Ubuntu like:

```
xhost local:root
```

- ros_entrypoint.sh

``` sh
#!/bin/bash
set -e

# setup ros environment
source "/opt/ros/noetic/setup.bash"
source "/ros_ws/devel/setup.bash"

exec "$@"
```

- docker compose.yml
```yml
version: '3'
services:
  cpp_test2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment: 
      - DISPLAY
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: roslaunch fields2cover_ros view_field.launch
```

- Dockerfile
```dockerfile
FROM osrf/ros:noetic-desktop-full

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    python3-dev \
    build-essential \
    lcov python3-tk swig \
    python3-catkin-tools

SHELL ["/bin/bash", "-c"]

EXPOSE 8000

RUN mkdir -p /ros_ws/src

RUN  source /opt/ros/noetic/setup.bash && \
                  cd /ros_ws/ && \
                  catkin init && \
                  catkin build && \
                  echo 'source /ros_ws/devel/setup.bash' >> ~/.bashrc && \
                  echo 'source /opt/ros/noetic/setup.bash' >> ~/.bashrc 

RUN cd /ros_ws && source /opt/ros/noetic/setup.bash && \
        git clone https://github.com/Fields2Cover/Fields2Cover src/fields2cover && \
        git clone https://github.com/Fields2Cover/fields2cover_ros src/fields2cover_ros && \
        rosdep install -r --ignore-src --from-paths . && \
        catkin build

COPY ./ros_entrypoint.sh /

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
```
</details>

**Comment by Gonzalo-Mier** [comment]
As Nav2 (@SteveMacenski) includes Fields2Cover in a proper ROS wrapper (https://github.com/open-navigation/opennav_coverage), we will declare fields2cover_ros unmaintained for now on.
