### ISSUE TITLE
Max_Icc and Set Radius

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#67]
So looking at this https://github.com/Fields2Cover/Fields2Cover/blob/cd0b5fcaef3587d239a0b1058d024e3096b6f531/docs/source/tutorials/basic_types.rst#L280 I realized the robot.max_icc is set by the `setMinRadius` function, but can also be accessed directly and modified. 

I ran into some unexpected behavior since I was calling `setMinRadius` but then also setting `max_icc` manually, which should be setting the same thing, essentially.

Would you be open to  making `max_icc` private to the robot and only allowing that value to be set via `setMinRadius` publically to prevent future confusion?

**Comment by Gonzalo-Mier** [comment]
Hi @vinnnyr, 

Thanks to point to this. Yes, indeed. For next release, it is planned to make all member private and create setters and getters for each of them. On the other hand, we didn't want to break the API constantly with small changes. So on the short term, both ways to access the same value stay.

Moreover, the `setMinRadius` and 'max_icc' case is a bit special. We think that the concept of the radius is more intuitive than the instantaneous curvature change (ICC). However, ICC is usually used for the computations. So we thought that having access for both methods was useful. Maybe, it should be explicitly mentioned in the documentation.

**Comment by Gonzalo-Mier** [comment]
This has been changed in the new version :)
