### ISSUE TITLE
How to get the swath endpoint

### ISSUE THREAD

**Issue by wannanfeng** [Fields2Cover/Fields2Cover#68]
Is there any way to get the endpoint coordinates of both ends of swath? 
Maybe it's because of my carelessness that I didn't see it in the python tutorial.

Just like the endpoint of one of the swaths in the picture (circled in red)

![image](https://github.com/Fields2Cover/Fields2Cover/assets/108105115/285981f5-d484-4532-b5c6-df953d7d337a)

Thank you!

**Comment by vinnnyr** [comment]
Can you try the `startPoint` and `endPoint` members of the `Swath` datatype? I think that will give you what you want
https://fields2cover.github.io/api/structf2c_1_1types_1_1Swath.html#_CPPv4NK3f2c5types5Swath10startPointEv

**Comment by Gonzalo-Mier** [comment]
Hi @wannanfeng, welcome to this project and I hope you are enjoying the library.

Thanks @vinnnyr for the support!

**Comment by wannanfeng** [comment]
@vinnnyr @Gonzalo-Mier 
Thank you!
After reading the link you gave, I think I have solved my problem.
Have a nice day!
