### ISSUE TITLE
Planning of Loops

### ISSUE THREAD

**Issue by vinnnyr** [Fields2Cover/Fields2Cover#75]
I have noticed that f2c plans loops for turns that seem tighter than what we would need.

![Figure_100](https://github.com/Fields2Cover/Fields2Cover/assets/22486686/9c6e53be-2a1b-4675-afaa-2d4b0a072fba)

Minimal example
```
import fields2cover as f2c

if __name__ == '__main__':
    # field
    rand = f2c.Random(42);
    field = rand.generateRandField(5, 1e4);
    cells = field.field;
    # robot
    robot = f2c.Robot(2.0, 2.0);
    robot.setMinRadius(1.0)
    # headlands
    const_hl = f2c.HG_Const_gen();
    no_hl = const_hl.generateHeadlands(cells, 3.0 * robot.robot_width);
    # swaths
    n_swath = f2c.OBJ_NSwath();
    bf_sw_gen = f2c.SG_BruteForce();
    swaths_bf_nswath = bf_sw_gen.generateBestSwaths(n_swath, robot.op_width, no_hl.getGeometry(0))
    # swath ordering
    boustrophedon_sorter = f2c.RP_Boustrophedon()
    swaths = boustrophedon_sorter.genSortedSwaths(swaths_bf_nswath)
    # path
    path_planner = f2c.PP_PathPlanning()
    dubins_cc = f2c.PP_DubinsCurvesCC()
    path_dubins_cc = path_planner.searchBestPath(robot, swaths, dubins_cc)
    # show
    f2c.Visualizer.figure(100)
    f2c.Visualizer.plot(path_dubins_cc)
    f2c.Visualizer.show()

```

This seems to happen for different turning radii as well. 
It definitely seems like maybe this is something related to the way f2c is using `steering_functions` dependency?

**Comment by Gonzalo-Mier** [comment]
Thanks for pointing to this. I was working on it tonight, and I found a solution to avoid the loops. Unfortunately, part of the code of the solution is from a person that is on holidays now (until July 17th), and I prefer to know if or how he would like to be a mentioned as a contributor. As soon as I have an answer, I would push it to main (aprox. 2 weeks), but you can assume this to be solved.

![Figure_100](https://github.com/Fields2Cover/Fields2Cover/assets/3874494/89676b3c-ad91-4c75-8559-908e9605278a)
