### ISSUE TITLE
Compilation steps are not rendered

### ISSUE THREAD

**Issue by groengpx** [Fields2Cover/Fields2Cover#77]
The compilation steps from the readme are not rendered (at least not on GitHub).

I am not an expert at .rst files, but the other code blocks in the readme *do* render, and they a have a blank line between the start of the code block and the content of the code block. So maybe that is the solution for the compilation code blocks as well?

**Comment by vinnnyr** [comment]
Can you take a screenshot? That's odd, I just looked and it seemed fine on my end.

**Comment by groengpx** [comment]
![screenshot](https://github.com/Fields2Cover/Fields2Cover/assets/90379523/9fbd275b-78fa-4656-ac73-543d6b2d9972)

**Comment by Gonzalo-Mier** [comment]
Hi @groengpx, thanks for contributing with this issue. It should be solved now :)

**Comment by vinnnyr** [comment]
> Can you take a screenshot? That's odd, I just looked and it seemed fine on my end.

I totally missed the section you were talking about lol.
