### ISSUE TITLE
Is it possible to use this library to plan a coverage path connecting multiple convex polygons?

### ISSUE THREAD

**Issue by AbdelrahmanAbdeldaim** [Fields2Cover/Fields2Cover#82]
I am trying to do coverage planning for a field with obstacles. My idea was to use convex decomposition to split the polygon into multiple convex shapes so I wouldn't have a problem with the obstacles. Can this library support making multiple fields from those polygons and then applying CPP for the connected polygons to generate one final path instead of multiple individual paths? If not, how can I define the start and end point for each coverage planning so I can use it in connecting the generated paths?

**Comment by vinnnyr** [comment]
see:
https://github.com/Fields2Cover/Fields2Cover/issues/11

There is a branch that does the decomposition, What is left is to connect the individual cells in the correct order

**Comment by AbdelrahmanAbdeldaim** [comment]
What does it mean for a field to have different cells? Isn't it enough to define it with one polygon (one cell defined by the coordinates of the outer points) since the planner is only able to solve for convex shapes?

**Comment by vinnnyr** [comment]
oh I understand now. I totally misunderstood you. It seems like the solution for #11  would be the same as the solution for your problem in that case (figuring out the correct swath order, and cell order to cover the field most efficiently).  

That solution is missing from the library right now. But the same solution could be applied to solve both problems.

**Comment by ingmeca2018** [comment]
Hi @AbdelrahmanAbdeldaim 

Did you find the solution for the issue plz?

Thanks

**Comment by Gonzalo-Mier** [comment]
[Fields2Cover can now handle with static obstacles and start-end points on the path](https://fields2cover.github.io/source/tutorials/route_planning.html)
