### ISSUE TITLE
AerialmapDisplay

### ISSUE THREAD

**Issue by Stoner-F** [Fields2Cover/Fields2Cover#83]
Dear author, 
What is the purpose of the AerialmapDisplay plugin in Rviz？ I am running `roslaunch fields2cover_ros view_field.launch `, it keeps displaying anomalies and there is no GPS API available. How can I solve this problem?
And the Error reported in terminal:
[ERROR] [1691649397.168491921]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: According to the loaded plugin descriptions the class rviz_plugins/AerialMapDisplay with base class type rviz::Display does not exist. Declared types are  rviz/AccelStamped rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/TwistStamped rviz/WrenchStamped rviz_plugin_tutorials/Imu

The Rviz display it like this...
![fields2cover](https://github.com/Fields2Cover/Fields2Cover/assets/107520266/8b3e3c05-2256-4cfc-beeb-70db764dece3)

I look forward to hearing from you soon. thank you!
Kind regards,
Finn

**Comment by Stoner-F** [comment]
On the other hand, Where to modify polygon boundary coordinate points?
In source code, `conversor::ROS::to(f.getCellBorder(0), polygon_st.polygon);`  is get polygon points, if I want to modify the boundary corrdinate points, what I shoud do?

**Comment by Gonzalo-Mier** [comment]
Hi @Stoner-F,
AerialmapDisplay (https://github.com/nobleo/rviz_satellite) returns the map from [OpenStreetMap](https://www.openstreetmap.org/). It is only required for visualization purposes.

`conversor::ROS::to(f.getCellBorder(0), polygon_st.polygon);` transforms `F2CLinearRing` into `geometry_msgs::Polygon`. `geometry_msgs::Polygon` are circular lines without holes (as `F2CLinearRing`). `f` is a `F2CCells`, which is a vector of `F2CCell`. And `F2CCell` is compound of `F2CLinearRing`s. The first one defines the outer border, and the others are the holes of the polygon. In general, compounded types in the Fields2Cover library have the method `size()` and `getGeometry(int)` to access to those values. Further documentation can be access [here](https://fields2cover.github.io/api/namespace_f2c__types.html#namespace-f2c-types).

Please, ask for any clarification if needed :)

**Comment by Gonzalo-Mier** [comment]
I'll close this issue. Feel free to re-open it if needed
