### ISSUE TITLE
questions about headland generator

### ISSUE THREAD

**Issue by wannanfeng** [Fields2Cover/Fields2Cover#86]
![W5AKU~JB0OA2LMMR6~YU`~V](https://github.com/Fields2Cover/Fields2Cover/assets/108105115/987bbd50-3886-46e6-948a-593b85f5f8a5)

Because I want to generator a new area outside the old area, so is there any way to get the area surrounded by blue lines?

Changing the later parameter in this code:  "no_hl = const_hl.generateHeadlands(cells, **3.0 * robot.robot_width**)" as "**-3.0 * robot.robot_width**" doesn't seem to work.

**Comment by wannanfeng** [comment]
Sorry to bother you again,
I don't seem to have solved this question, I used this code **apt install libgeos-dev** to make sure the library function is up to date, but when I tried this code:
**no_hl = const_hl.generateHeadlands(cells, (-1) * 3.0 * robot.robot_width)**
I didn't get the blue polygon that I got by expanding the original orange polygon.
Just multiplying by minus one gets the polygon to coincide with the original polygon, it seems doesn't work.

**Comment by Gonzalo-Mier** [comment]
Hi @wannanfeng,

Have you removed the `build` folder before compiling it again?

```
import fields2cover as f2c

rand = f2c.Random(42);
field = rand.generateRandField(5, 1e4);
cells = field.field;
robot = f2c.Robot(2.0, 26.0);

const_hl = f2c.HG_Const_gen();
no_hl = const_hl.generateHeadlands(cells, 3.0 * robot.robot_width);
outer_hl = const_hl.generateHeadlands(cells, -3.0 * robot.robot_width);
print("The complete area is ", cells.getArea(),
    ", and the area without headlands is ", no_hl.getArea(),
    ", and the area with outer headlands is ", outer_hl.getArea());
 
f2c.Visualizer.figure()
f2c.Visualizer.plot(cells,"r")
f2c.Visualizer.plot(no_hl,"b")
f2c.Visualizer.plot(outer_hl,"k")
f2c.Visualizer.show()
```

The previous code should return this image:

![example](https://github.com/Fields2Cover/Fields2Cover/assets/3874494/152f5d49-7aa3-4a51-805a-d6b997cce0f4)

**Comment by wannanfeng** [comment]
Thank you very much for your answer！
I'm sorry I didn't solve it, I'm a freshman undergraduate and I'm not familiar with this field.
I have run the code you provided, and the output is as follows:

**The complete area is  9999.999999999998 , and the area without headlands is  7709.941497354909 , and the area with outer headlands is  10000.000000000002**
The outer area and the original area still seem to coincide.
Do you mean the build folder is circled in red? Should I remove it all?
<img width="870" alt="1692797303743" src="https://github.com/Fields2Cover/Fields2Cover/assets/108105115/40c34af3-cc0c-4218-8a74-8311ac2166f2">

**Comment by Gonzalo-Mier** [comment]
Did it work for you?

**Comment by wannanfeng** [comment]
Sorry, I have already achieved my purpose by other methods before I asked you this question, so I didn't uninstall it because I wasn't familiar with Linux and it took a lot of time to install Field2Cover for the first time. 
If I want to implement this function next time, I will try what you said and report back to you whether it is successful. Thank you for your help！
