### ISSUE TITLE
Can F2C work with wgs84 coordinates?

### ISSUE THREAD

**Issue by groengpx** [Fields2Cover/Fields2Cover#87]
My input (the field boundary and headlands) are in wgs84, and my output (the final path) should also be in wgs84 coords. But all functions in the F2C api seem to work with X, Y (local) coords. What should I do?

**Comment by Gonzalo-Mier** [comment]
Hi @groengpx, welcome to the project!!
Yes, Fields2Cover works on local coordinates. Fortunately, the library provides the class [Transform](https://fields2cover.github.io/api/classf2c_1_1Transform.html) to transform the coordinate system safely. 

As an example:
```
F2CField field = ...; // Import your field
field.setEPSGCoordSystem(4326);  // WGS84 is EPSG:4326
f2c::Transform::transform(field, "EPSG:28992");  // Transform the field to a coordinate system that works in meters (28992 is from NL)
// ... Compute the path ...
 auto returned_path2 = f2c::Transform::transformPathWithFieldRef(path2, field, "EPSG:4326"); // Return the path to WGS84
```

Remember that this is an example to show the conversion between WGS84 to any EPSG coordinate system. If you were really working on NL, coordinate values should be recorded and saved on ETRS89 (EPSG:4258).

**Comment by groengpx** [comment]
Ah, thanks.

But then I need to know the local system of each country. Do you think I can get away with UTM zones? For example, when starting with a transformation, I check in which UTM zone the first coordinate is (let's say N31 (epsg:32631)) and then use that zone for the transformations (instead of epsg:28992 in your example).

**Comment by Gonzalo-Mier** [comment]
This should work `f2c::Transform::transform(field, "UTM:31N datum:WGS84")`, but I haven't tested in depth

**Comment by Gonzalo-Mier** [comment]
@groengpx Did it solved your problem? :)

**Comment by groengpx** [comment]
Haven't got time yet, but it seems to be a good solution. I will close this for now. If it won't work, I will reopen.
