### ISSUE TITLE
Connecting between two fields

### ISSUE THREAD

**Issue by ingmeca2018** [Fields2Cover/Fields2Cover#88]
Hi Gonzalo,

Is there any function which connect between two or more fields? (generate a path between the last point of field "A" and first point of field "B")

Thanks

**Comment by Gonzalo-Mier** [comment]
Hi @ingmeca2018, 
No, unfortunately this is one of the issues why non-convex fields are not supported yet.

**Comment by ingmeca2018** [comment]
thank you @Gonzalo-Mier.

Yes, I've read the issues 11 and 82 and I was hoping to get some progress on this subject.

My application is not complicated, it 's based on the connection between simple fields (file attached) so I thought it could be easier
 for this case.
![F2c](https://github.com/Fields2Cover/Fields2Cover/assets/129290403/c1401c1e-2bf2-4adc-9c44-01b3cf3d45d2)


I'll close the issue, hoping for good news soon.
Thanks

**Comment by Gonzalo-Mier** [comment]
No, please, leave it open as it is not solved. According to the example you provided, how should it go from one point to the other? If it is the shortest path, you can concatenate all the `F2CSwath`s of all the fields in a common `F2CSwaths`, and plan a path with a path planner :) I hope this help

**Comment by ingmeca2018** [comment]
Thanks for your feedback.
Yes, I think it's a good idea for this example.
I'll try this and keep you posted.
Thank you @Gonzalo-Mier

**Comment by Gonzalo-Mier** [comment]
I'll close this issue then :) Feel free to open it again
