### ISSUE TITLE
Deactivate headland

### ISSUE THREAD

**Issue by Marnonel6** [Fields2Cover/Fields2Cover#90]
Hi,

Is there a way to deactivate the headland and only have the swafts? My understanding from my agriculture experience is that a vehicle will first drive the headlands and then the swafts. Is this the same with the path planner does it contain the headland and then the swafts? Reason that I do not want a headland is I'm using a drone to survey a field and thus do not need to fly the headland.

Best,
Marno

**Comment by Gonzalo-Mier** [comment]
Hi Marno, welcome to the project!

Right now F2C doesn't have any way to cover the headlands. It just reserve
that space for them. If you want to use it without headlands, you can
simply not use the headland generator module (or create a headland with 0
width).

**Comment by Marnonel6** [comment]
Thank you very much! After doing all the C++ tutorials I understand the package a lot more! Well done with the package and paper!
