### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by Marnonel6** [Fields2Cover/Fields2Cover#91]
I am looking at the ROS2 (Humble) support for this package, but it looks like it is mainly ROS1? It's fine I'll just use the C++ library then and integrate it with ROS2, but if I am missing the ROS2 support please point it out.

Thank you

**Comment by Gonzalo-Mier** [comment]
Hi @Marnonel6, the ROS support was designed for ROS 1. Either way those messages can be also used in ROS 2. @SteveMacenski is working in a Nav2 Integration (#73), but it's not ready yet.

**Comment by Marnonel6** [comment]
Thank you for the update! I'll write a ROS2 wrapper for the C++ implementation.
