### ISSUE TITLE
Exported path discritization

### ISSUE THREAD

**Issue by Marnonel6** [Fields2Cover/Fields2Cover#92]
Hi,

I am currently exporting the path that is generated. I noticed that the X,Y values do not change significantly along a swath, but jump from one end-point to another in my case from 100-0. Around the corners between swath's the X,Y values do change. I think my problem is the same as the issue [here](https://github.com/Fields2Cover/Fields2Cover/issues/57). I tried using `path_dubins_cc.serializePath(0.1);`, but I am not sure how to use it. Did not effect the results. 

# Code

      #include "fields2cover.h"
      #include <iostream>
      
      int main() {
          // Define field and robot
          f2c::Random rand(42);
          F2CRobot robot (1.0, 4.0);
          f2c::hg::ConstHL const_hl;
          F2CCells cells(F2CCell(F2CLinearRing({F2CPoint(0,0), F2CPoint(0,100), F2CPoint(40,100),
                                                  F2CPoint(40,0), F2CPoint(0,0)})));
      
          // Swath generation
          std::cout << "####### Tutorial 5.1 Boustrophedon ######" << std::endl;
          f2c::sg::BruteForce bf;
          F2CSwaths swaths = bf.generateSwaths(M_PI, robot.op_width, cells.getGeometry(0));
          f2c::rp::BoustrophedonOrder boustrophedon_sorter;
          auto boustrophedon_swaths = boustrophedon_sorter.genSortedSwaths(swaths);
      
          // Path planner
          f2c::pp::PathPlanning path_planner;
          robot.setMinRadius(2.0);  // m
          robot.linear_curv_change = 0.5;  // 1/m^2
      
          // Create swath connection curves
          std::cout << "####### Tutorial 6.2 Dubins curves with Continuous curvature ######" << std::endl;
          f2c::pp::DubinsCurvesCC dubins_cc;
          F2CPath path_dubins_cc = path_planner.searchBestPath(robot, boustrophedon_swaths, dubins_cc);
      
          std::cout << "Path length \n" << path_dubins_cc.length() << std::endl;
      
          // Save to file
          path_dubins_cc.serializePath(0.1);
          path_dubins_cc.saveToFile("path_1.csv");
      
          f2c::Visualizer::figure();
          f2c::Visualizer::plot(cells);
          // f2c::Visualizer::plot(no_hl);
          f2c::Visualizer::plot(path_dubins_cc);
          f2c::Visualizer::plot(boustrophedon_swaths);
          f2c::Visualizer::show();
          f2c::Visualizer::save("complete_path");
      
          return 0;
      }

# Image
![image](https://github.com/Fields2Cover/Fields2Cover/assets/60977336/67853ee7-f8d3-46d5-aa63-cb6bf3624756)

# Path transition Y value from 100 to 0
![image](https://github.com/Fields2Cover/Fields2Cover/assets/60977336/94031319-f79f-4aa7-9f65-9f48f1050eca)

# Exported path (Partially)
[path_1.txt](https://github.com/Fields2Cover/Fields2Cover/files/12772665/path_1.txt)

**Comment by Gonzalo-Mier** [comment]
If you have made the swaths with F2C, they are straight line. So only two
points are required to represent them (start and end).
On the serialized path, only points in which the direction changes are
represented. Does it help? :)

**Comment by Marnonel6** [comment]
Okay this makes sense. Is there a way to make the swaths discretized as well with the current implementation of the code base? The main reason for this is I want to have intermediate way points along the swath to navigate to instead of just navigating to the end point of the swath which in my case is 100[m] away.

Otherwise would you be open to a PR if I implement this functionality?

**Comment by Gonzalo-Mier** [comment]
There's no way right now. Feel free to create a PR. We are always happy to
improve the library.

**Comment by Marnonel6** [comment]
Pull request merge for this issue:
https://github.com/Fields2Cover/Fields2Cover/pull/93#issue-1921001928
