### ISSUE TITLE
New discretize_swath() function import issue to cpp/ROS2 package

### ISSUE THREAD

**Issue by Marnonel6** [Fields2Cover/Fields2Cover#94]
Hi,

So am am trying to use the new discretize_swath() function with a new cpp package, but I am running into the problem below only for the discretize_swath() function, all of the other functions work.

Is there something missing to make this function work in different external packages that I need to add?

## Problem when using `colcon build`

`
      error: ‘using F2CPath = struct f2c::types::Path’ {aka ‘struct f2c::types::Path’} has no member named ‘discretize_swath’
         28 |     F2CPath new_path = path_dubins_cc.discretize_swath(discretize_step_size);
            |                                       ^~~~~~~~~~~~~~~~
      gmake[2]: *** [CMakeFiles/test_c.dir/build.make:76: CMakeFiles/test_c.dir/src/test_c.cpp.o] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/test_c.dir/all] Error 2
      gmake: *** [Makefile:146: all] Error 2
      ---
      Failed   <<< drone_control [1.13s, exited with code 2]
`

## The cpp file I am using the Fields2Cover package in: `test_c.cpp`

      #include "fields2cover.h"
      #include <iostream>
      
      int main() {
          // Define field, headland and robot
          F2CRobot robot (2.0, 5.0);
          F2CCells field(F2CCell(F2CLinearRing({F2CPoint(0,0), F2CPoint(0,100), F2CPoint(40,100),
                                                F2CPoint(40,0), F2CPoint(0,0)})));
      
          // Swath generation
          f2c::sg::BruteForce bf;
          f2c::obj::NSwath n_swath_obj;
          F2CSwaths swaths = bf.generateSwaths(M_PI, robot.op_width, field.getGeometry(0));
          f2c::rp::BoustrophedonOrder boustrophedon_sorter;
          auto boustrophedon_swaths = boustrophedon_sorter.genSortedSwaths(swaths, 1);
      
          // Path planner
          f2c::pp::PathPlanning path_planner;
          robot.setMinRadius(2.5);  // m
      
          // Create swath connections using Dubins curves with Continuous curvature
          f2c::pp::DubinsCurvesCC dubins_cc;
          F2CPath path_dubins_cc = path_planner.searchBestPath(robot, boustrophedon_swaths, dubins_cc);
      
          // Discretize swath lines in path object
          // Specify the step size and the robot velocity for the swath section
          double discretize_step_size = 25; // Step size for discretization in [m]
          F2CPath new_path = path_dubins_cc.discretize_swath(discretize_step_size);
      
          // Save to file
          new_path.saveToFile("discretized_swath_path.csv", 5); // Specify precision to the significant number
      
          // Visualize
          f2c::Visualizer::figure();
          f2c::Visualizer::plot(field);
          // f2c::Visualizer::plot(no_hl);
          f2c::Visualizer::plot(new_path);
          f2c::Visualizer::plot(boustrophedon_swaths);
          f2c::Visualizer::show();
          // f2c::Visualizer::save("discretized_swath_figure");
      
          return 0;
      }

## CMakeLists.txt

      find_package(Fields2Cover REQUIRED)
      # Path planning node
      add_executable(test_c src/test_c.cpp)
      target_link_libraries(test_c Fields2Cover) # Link Fields2Cover library
      ament_target_dependencies(test_c Fields2Cover)
      install(TARGETS test_c DESTINATION lib/${PROJECT_NAME})

## package.xml

     <depend>Fields2Cover</depend>

## Folder layout
    ros2_ws/
        src/
            Fields2Cover/
                    (Main branch)
            drone_control/
                    src/
                        test_c.cpp (Code that includes Fields2Cover package)
            CMakeList.txt
            package.xml

## Installed Fields2Cover
        mkdir -p build;
        cd build;
        cmake -DCMAKE_BUILD_TYPE=Release ..;
        make -j$(nproc);
        sudo make install;

**Comment by Gonzalo-Mier** [comment]
It seems like it's getting the reference of a previous F2C library. Try to
do again 'sudo make install' and delete previous compilations of ROS 2.

**Comment by Marnonel6** [comment]
Worked thank you! Forgot the simple fix of `rm -rf build/ install/ log/`.
