### ISSUE TITLE
LineString() Points with wgs84 coordinates instead of X, Y ?

### ISSUE THREAD

**Issue by ingmeca2018** [Fields2Cover/Fields2Cover#96]
Hello @Gonzalo-Mier ,

I want to generate a dubin_path to relate a Multiple f2c.LineString()(it's not a field, see the simple example bellow).
The input "Lines_Points" are in X, Y. What should i do to work with wgs84 coords instead of X, Y ?

............................................................................................
import math
import fields2cover as f2c

path0 = f2c.LineString();
path1 = f2c.LineString();
path2 = f2c.LineString();
path3 = f2c.LineString();

path0.addPoint( 0.0, 0.0);
path0.addPoint( 0.0, 10.0);
path1.addPoint( 10.0, 20.0);
path1.addPoint( 10.0, 30.0);
path2.addPoint( 30.0, 30.0);
path2.addPoint( 30.0, 20.0);
path3.addPoint( 45, 5.0);
path3.addPoint( 35, 5.0);

swath0 = f2c.Swath(path0);
swath1 = f2c.Swath(path1);
swath2 = f2c.Swath(path2);
swath3 = f2c.Swath(path3);
swaths = f2c.Swaths();

[swaths.push_back(i) for i in [swath0, swath1, swath2, swath3]]

robot = f2c.Robot();
robot.cruise_speed = 1.0;
robot.setMinRadius(4);

path_planner = f2c.PP_PathPlanning();
dubins = f2c.PP_DubinsCurves();
dubins_path = path_planner.searchBestPath(robot,swaths,dubins);
..................................................................................................

**Comment by Gonzalo-Mier** [comment]
If your reference point for the GPS is '(A, B)', and your UTM zone is 32N, then:

```
gps_ref = f2c.Point(A, B)
ref_xy = f2c.Transform.transform(gps_ref, "EPSG:4326", "UTM:32N datum:WGS84")
dubins_path.moveTo(ref_xy)
gps_path = f2c.Transform.transform(dubins_path, "UTM:32N datum:WGS84", "EPSG:4326")
```

**Comment by ingmeca2018** [comment]
@Gonzalo-Mier Thanks for your reply.
I got this error :     
"ref_xy = f2c.Transform.transform(gps_ref, "EPSG:4326", "UTM:32N datum:WGS84")
TypeError: transform() takes 2 positional arguments but 3 were given"

Other question : As you see, every time i add a start.point and end.point to the path[i] to make a Line (example path0.addPoint( 5.0, -30.0), path0.addPoint( 0.0, 10.0))
Because in my application i should give them in GPS coordinates instead of (X,Y) like the simple example on top, adding the gps-ref to the code is the only change that should be done?

**Comment by Gonzalo-Mier** [comment]
Sorry, the swig interface doesn't allow that yet. Recompile the f2c library, install it and try this:

```
gps_ref = f2c.Point(4.261999903178513,51.785970497504699)
field = f2c.Field()
field.setRefPoint(gps_ref)
f2c.Transform.transformToUTM(field)
path = f2c.Transform.transformToPrevCRS(dubins_path, field)
```
It should work now

**Comment by ingmeca2018** [comment]
@Gonzalo-Mier ,

Thanks, yes it works.
So, i can put directly the points of the swaths (path[i].addPoint(.....,.....) in the example) in gps coords ?

**Comment by Gonzalo-Mier** [comment]
I don't understand what you want

**Comment by ingmeca2018** [comment]
it's for panning a simple trajectory (not to cover a field)
In fact, you have to pass through specific points.
So I build the swaths from these points (I know the position of these points, so each swath will be presented by two consecutive points).

![test0](https://github.com/Fields2Cover/Fields2Cover/assets/129290403/9ff97045-c6d4-4cb4-b359-98aa40632851)


In the example, the coordinates of these points are given in (X, Y). In reality, these coordinates will be given in GPS coordinates.
It's possible?

**Comment by Gonzalo-Mier** [comment]
I'll close the issue as it was solved. Feel free to open a new one if you have more doubts :)
